### ISSUE TITLE
How can I use `on_setup` on window

### ISSUE THREAD

**Issue by deadash** [klemens-morgenstern/boost-process#100]
The following example won't work
```
    bp::system("test.exe",
        bp::on_setup([](auto &e)
            { e.startup_info.dwFlags = STARTF_RUNFULLSCREEN; }),
        bp::on_error([](auto&, const std::error_code & ec)
            { std::cerr << ec.message() << std::endl; })
        );
```

and also as `bp::extend::on_setup` 

I want to know how to set startup info.

**Comment by klemens-morgenstern** [comment]
Won't work as in give you a compile error or as in doing nothing? Because that looks find to me.

**Comment by deadash** [comment]
`bp::on_setup` not found in any where.
`bp::extend::on_setup` compile error. I don't know how to call it.

And I found the `group_ref` maybe is I want.(I want to exit child process when parent exit.)
But I don't know how to use it.

**Comment by klemens-morgenstern** [comment]
That should work:

```
#include <boost/process/system.hpp>
#include <boost/process/extend.hpp>

int main(int argc, char * argv[])
{
    return 
  bp::system("test.exe",
        bp::extend::on_setup([](auto &e)
            { e.startup_info.dwFlags = STARTF_RUNFULLSCREEN; }),
        bp::extend::on_error([](auto&, const std::error_code & ec)
            { std::cerr << ec.message() << std::endl; })
        );
}
```

If you want to bind several processes you can put them in a [group](http://klemens-morgenstern.github.io/process/boost_process/tutorial.html#boost_process.tutorial.group), which internally uses the `group_ref`. That might however not do what you actually want.

https://github.com/klemens-morgenstern/boost-process/blob/develop/test/extensions.cpp

**Comment by deadash** [comment]
many thanks!!!

it's work.but how to use it in `bp::child`

**Comment by klemens-morgenstern** [comment]
Same way:

```
bp::child ch("test.exe",
        bp::extend::on_setup([](auto &e)
            { e.startup_info.dwFlags = STARTF_RUNFULLSCREEN; }),
        bp::extend::on_error([](auto&, const std::error_code & ec)
            { std::cerr << ec.message() << std::endl; })
        );
```

**Comment by deadash** [comment]
I figure out what my problem is.

I have too many parameters over 10.(just 11, so delete one will work well.)

thanks again.

**Comment by klemens-morgenstern** [comment]
Oh, you're using the microsoft compiler :D
Well yeah, that's not C++11 compliant, thus using strange workarounds with the variadics.

**Comment by deadash** [comment]
yeah, I use Visual Studio 2017.

**Comment by deadash** [comment]
I post the way how to exit child process when parent process exit.
maybe for someone can use it.

```
void init()
{
    	gJob = CreateJobObject(NULL, NULL);

	if (gJob) {
		JOBOBJECT_EXTENDED_LIMIT_INFORMATION jl = { 0 };
		jl.BasicLimitInformation.LimitFlags = JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;
		if (TRUE == SetInformationJobObject(gJob, JobObjectExtendedLimitInformation, &jl, sizeof(jl))) { bJob = true; }
	}
}

void run()
{
	_child = bp::child(
		...,
		bp::extend::on_setup([](auto &e)
	{ e.startup_info.dwFlags |= /*CREATE_SUSPENDED | */CREATE_BREAKAWAY_FROM_JOB; }),
		...
	);

	// add to job & not support below on xp.
	if (bJob) {
		AssignProcessToJobObject(gJob, _child.native_handle());
	}
}
```

its work well.

**Comment by klemens-morgenstern** [comment]
Yeah, that's how group is implemented on windows.

**Comment by deadash** [comment]
yes, your library is powerful.Help us many.
