### ISSUE TITLE
Make it clear which repository is the "main one"

### ISSUE THREAD

**Issue by ldionne** [klemens-morgenstern/boost-process#101]
Right now, it's not clear where to submit PRs because https://github.com/boostorg/process is not a fork or anything like that.

**Comment by klemens-morgenstern** [comment]
I know, I actually wrote github support to turn the other one into a fork. Rene didn't have the authorization to do that, so in case you know who does, I'd greatly appreciate it.

**Comment by ldionne** [comment]
Strange, I thought Rene would have permissions for that. You can close this.
