### ISSUE TITLE
Documentation: No list of compatible/supported compilers

### ISSUE THREAD

**Issue by timpatt** [klemens-morgenstern/boost-process#103]
I've just been trying to get Process to run on Visual Studio 2010.  The top-level page (http://www.boost.org/users/history/version_1_64_0.html) suggests that this compiler is supported but comments on other issues on this repository suggest that this is not the case for this library.  There doesn't seem to be any indication as to what compilers/platforms are actually supported!

Perhaps a list of supported/tested compilers/platforms somewhere near the top of the process documentation would be useful - maybe with a justification as to why some don't make the cut...

**Comment by klemens-morgenstern** [comment]
It's a C++11 library, so compiler that don't support C++11 are not supported - it's as simple as that.

**Comment by timpatt** [comment]
Fair enough... But where in the documentation does it mention that?

**Comment by klemens-morgenstern** [comment]
Oh yeah, that's not mentioned in the docs, but it's in the readme though. I might need to add a note to the introduction.

Why would you use VS2010 in 2017 anyway?

**Comment by timpatt** [comment]
We're a slave to our closed-source dependencies, and a surprisingly large number are still stuck back in the dark ages :-(

**Comment by klemens-morgenstern** [comment]
Well you certainly have sympathy. Thing is: my library is built following the C++11 standard and NOT specific compilers. I.e. I give you a guarantee that it'll work with C++11, but I won't check every compiler; if you have a compiler with partial support it's a matter of luck. Actually VS 2013 doesn't work either, but there could be a workaround written, if anybody does that in a proper way, I'll add it.

**Comment by klemens-morgenstern** [comment]
I.e. it uses `noexcept` and `ref-value qualifiers` which could be worked around, but that currently breaks VS2013.
