### ISSUE TITLE
Redirect std_out to std::future<std:string> causing exception

### ISSUE THREAD

**Issue by JonHodgson** [klemens-morgenstern/boost-process#105]
Ok, so I have a function to run mercurial and capture the output in a string.

So far as I can see, I've done what the examples show as regards redirect the output.

```
std::string execute_hg(std::vector<std::string> args, const char* path) 
{
	boost::asio::io_service ios;
	std::future<std::string> output;
	args.insert(args.begin(), boost::process::search_path("hg").string());
	args.push_back(path);
	boost::process::system(args,
		boost::process::std_out > output, ios,
		boost::process::std_in  < boost::process::null,
		boost::process::std_err > boost::process::null		
	);
	return output.get();
}
```

when I run it (on WIndows 10, Visual Studio 2015 32 bit build) I get an exception when it tries to run system().

0xC0000008: An invalid handle was specified.

Now, I can add that it is being called with the correct arguments for hg, if I change the code to redirect to file with 
boost::process::std_out > "checkoutput.txt"
Then I see exactly the result I expect, in fact if I look at the value of output when the exception is thrown, it appears to contain the expected output.

**Comment by klemens-morgenstern** [comment]
Thanks for the report, I'M a bit confused by the issue-title though. So you want to redirect to an ´std::future<std::string>´ not an `std.:string`?

**Comment by JonHodgson** [comment]
std::future<std::string> seems to be the way to do it according to the documentation?

I've only just started using this new version of boost::process, my previous code for this was using a pipe and a file_descriptor_sink, I'm flying a bit blind at the moment, so I just copied what I saw.

From the io.hpp documentation (though I think that last line has a typo and should be output.get() ?
```
boost::asio::io_service ios;
std::future<std::string> output;
system("ls", std_out > output, ios);

auto res = fut.get();
```
Ok, I just tried making output a std::string and removing the ios parameter and it's empty at after system(), so that's not the way it seems.

**Comment by klemens-morgenstern** [comment]
So, your code is correct and I will need to take a deeper look into that.
But I think you wouldn't want to use system and future, because system is synchronously. You could use spawn and future though. That will put the output in the future when the process finished and you won't need a handle. The other thing you can do with system is to use a buffer, e.g. `asio::streambuf`.

```
boost::asio::io_service ios;
boost::asio::streambuf output;
system("ls", std_out > output, ios);

std::istream is(&output);

//read from is
```

That would be a synchronous solution.

**Comment by inzaghi250** [comment]
Having the same problem.

**Comment by krwalker** [comment]
I believe this may have been fixed in 74814e46c1614850a8e447fd689c21cf82f36ceb, the same fix for #90, as I no longer get the exception when running in the IDE after applying the patch.

**Comment by klemens-morgenstern** [comment]
@JonHodgson Can you confirm?

**Comment by kenkit** [comment]
I use this https://github.com/boostorg/process/issues/89
but there is just a small catch, can't get the whole output just the first line, don't know why

**Comment by klemens-morgenstern** [comment]
Closing, unifying issues at [boostorg/process](https://github.com/boostorg/process).

This whole design was a mistake, I would recommend using an async_pipe with async_read instead.

Please reopen it there.
