### ISSUE TITLE
Crash when redirecting to std::future<std::string> and process has no output

### ISSUE THREAD

**Issue by mika-fischer** [klemens-morgenstern/boost-process#106]
I think the problem is in https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/async_out.hpp#L142

```std::istream is (buffer.get());
Type arg;
arg.resize(buffer->size());
is.read(&*arg.begin(), buffer->size());

promise->set_value(std::move(arg));
```

When `buffer->size() == 0`, invoking `*arg.begin()` is UB.

If I put an `if (!arg.empty())` in there, that fixes the crash for me.

**Comment by klemens-morgenstern** [comment]
Hey Mika, thanks. I assumed that would work since it's zero, but you're right. I'll add a fix including a test soon.
