### ISSUE TITLE
Not create hidden window on OS Windows

### ISSUE THREAD

**Issue by heretic13** [klemens-morgenstern/boost-process#107]
Hello.

I'm trying to create a process that does not have a window.
But I can not.

::boost::process::environment env = ::boost::this_process::environment();
::boost::process::child ch1("cmd", env, ::boost::process::windows::hide);

I got a tip from here, but it does not work.
https://stackoverflow.com/questions/43582022/boostprocess-hide-console-on-windows

PS: I use official boost-1.64

**Comment by klemens-morgenstern** [comment]
That could be because of cmd, I'm not sure. I checked the code, that looks correct to me. Can you try it with some other application like notepad?

**Comment by heretic13** [comment]
Hm. It's working for notepad.
Strange

**Comment by heretic13** [comment]
I think I understand. This does not work for console programs.
boost::process::child ch1("d:/Utils/bc/bc.exe", env, ::boost::process::windows::hide);
where bc is port of linux bc calculator (http://gnuwin32.sourceforge.net/packages/bc.htm)

**Comment by klemens-morgenstern** [comment]
Yeah that's the strange way windows groups gui and console programs.

**Comment by heretic13** [comment]
THIS SHOULD NOT BE CLOSED!
IT SHOULD BE CORRECTED!
This is a bug in your library. Opening console programs under Windows OS without a window is normal behavior and commonly used practice.

Here's a working example (pure WinAPI).

int main()
{
	PROCESS_INFORMATION ProcessInfo; //This is what we get as an [out] parameter

	STARTUPINFO StartupInfo; //This is an [in] parameter

	ZeroMemory(&StartupInfo, sizeof(StartupInfo));
	StartupInfo.cb = sizeof StartupInfo; //Only compulsory field

	if (CreateProcess(L"d:/Utils/bc/bc.exe", NULL,
		NULL, NULL, FALSE, CREATE_NO_WINDOW, NULL,
		NULL, &StartupInfo, &ProcessInfo))
	{
		WaitForSingleObject(ProcessInfo.hProcess, INFINITE);
		CloseHandle(ProcessInfo.hThread);
		CloseHandle(ProcessInfo.hProcess);
	}
	else
	{
		MessageBox(nullptr, L"The process could not be started...", L"Error", MB_OK);
	}

	return 0;
}

PS: Do not act like other boost-developers . You must understand & fix the problem and do not rush to close the issue.

**Comment by klemens-morgenstern** [comment]
Dude I'm working on an open-source library in my free time. If you want something in the library, fork it, provide a pull request with a fix. Your sense of entitlement is not welcomed here.

Now regarding your example ,that's precisely what my library is doing when you start without the show-windows parameter. `hide` is applied as described in the docs, which means it sets the flag `SW_HIDE` on the startupinfo. It's not part of the core library, it's a windows extension.

So if you don't like it, go jump in a lake.

**Comment by heretic13** [comment]
Religion does not allow Boost-developers to keep several issues open?
Do you lose the crown if you have more than 10 or 20 unsolved problems?
