### ISSUE TITLE
Win32 exception on extremely simple program

### ISSUE THREAD

**Issue by heretic13** [klemens-morgenstern/boost-process#108]
Very simple program:

boost::asio::io_service ios;
boost::process::async_pipe ap(ios);

Raises an exception under Win32-debugging.

https://www.dropbox.com/s/alzersekusvj9lv/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-07-11%2001.11.41.png?dl=0

**Comment by klemens-morgenstern** [comment]
Please copy your code properly here and don't post dropbox links. You can also embed pictures in markdown.

**Comment by klemens-morgenstern** [comment]
Also closed in 74814e46c1614850a8e447fd689c21cf82f36ceb
