### ISSUE TITLE
POSIX details questions

### ISSUE THREAD

**Issue by keith-bennett-gbg** [klemens-morgenstern/boost-process#116]
Hi @klemens-morgenstern 

This is somewhat related to #112. Perhaps I'm misunderstanding how POSIX multi-process or `waitpid` works. I figured I'd ask some questions. It appears to be questions/comments on the `develop` branch so my apologies if they're about an inaccurate representation of current or future library plans.

In `boost::process::detail::posix`, there's several `wait` wrapper functions.

1. [Here](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/posix/wait_for_exit.hpp#L29), it would appear to me that the call to `waitpid()` would only ever return `-1` or the same pid that was returned to it. If my understanding is correct, then the child must have exited if `p.pid` was returned. So, why check for `WIFEXITED()` and `WIFSIGNALED()`?

1. [Here](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/posix/wait_for_exit.hpp#L32-L33), I am concerned that the `throw` is inconsistent. There are plenty of other calls to `waitpid()` which check for `WIFEXITED` and/or `WIFSIGNALED` but don't throw, even ones without a `std::error_code`.

    * First, I don't think a throw for `WIFSIGNALED` is appropriate, since the program exiting because of a signal is _a part of the program's exit status_. It's an important detail and _may be normal behavior_. One example off the top of my head includes `tail -f` being killed to terminate output. Because of the throw, the terminating signal number (available with `WTERMSIG(status)`) is lost. It describes that the process indeed does not exist (and was reaped) and that it did not exit via returning from `main()` or a call to `exit()` but was instead _interrupted_ and terminated by a signal. Sort've like buying an open-box at a retail store... perhaps not everything is as it should be... perhaps that file you asked the process to work on was left in an undefined and inconsistent state. This is an important piece of information.

    * Second, even if you don't throw, the terminating signal number is [masked out by `eval_exit_status()`](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/posix/is_running.hpp#L71-L74) when [called by `child::exit_code()`](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/child_decl.hpp#L99). I'm not sure that's correct behavior either, unless there's some other exposed method to retrieve the terminating signal number. Using `grep -nR WTERMSIG include/` I do not see one.

1. It looks like the code in `wait_for_group.hpp` exhibits pretty similar problems. I can't admit to knowing how process _groups_ work, but [the error message in this exception thrown](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/posix/wait_group.hpp#L32) makes it sound like _all processes in the group have exited_. I don't believe that to be an accurate statement though. My instinct and understanding of [documentation](https://linux.die.net/man/2/waitpid) me tells me that the return value of `waitpid()` when given a group ID would be to return the process ID (and status) of _one_ of the processes from that group that has changed state. Along those lines, if more than one child process in the group needs to be reaped, then `waitpid()` would need to be called multiple times. Disappointingly, it looks like the group versions of `wait` and `wait_for` eat both the exited process ID as well as its exit status.

1. [`WUNTRACED` is passed to group `waitpid()`](https://github.com/klemens-morgenstern/boost-process/blob/66989a25f2ab069cccacf5489e54210092d97d8e/include/boost/process/detail/posix/wait_group.hpp#L129-L159) but with the above issues there's no way to identify that a child has been suspended; instead it would appear that a child has exited.

I might make a pull request to try to address some of these issues if they are indeed issues and not just me misunderstanding how to use the library.

**Comment by klemens-morgenstern** [comment]
Can this be closed since #138 is merged?

**Comment by keith-bennett-gbg** [comment]
Hi @klemens-morgenstern 

Thanks for following up. I was hoping for a conversation to help me understand design rationales for some of these.

I must have missed the merge notification for #138 . I'm glad there's some work that was done to help resolve this.

Unfortunately it looks like there's some bugs in that merge. The `noexcept` specifier [here](https://github.com/klemens-morgenstern/boost-process/blob/342554b3d841ba29df7365b1b5273122ab59fe16/include/boost/process/detail/posix/wait_for_exit.hpp#L90) and [here](https://github.com/klemens-morgenstern/boost-process/blob/342554b3d841ba29df7365b1b5273122ab59fe16/include/boost/process/detail/posix/wait_for_exit.hpp#L112) will cause `std::terminate` to be called if an exception is ever thrown by `boost::process::detail::throw_error()`. I very strongly believe that to be erroneous behavior.

**Comment by klemens-morgenstern** [comment]
I do love some good technical discussion, but they are sadly time consuming. And I didn't want to give some bad answer, so uhm, that issue got a bit lost. sry 'bout that.

The main rationale is that it's a library that wraps around posix AND windows and that concerns around exceptions can be mitigated using `std::error_code`. If you have a proposal how to improve something I'll gladly look at it, but I don't have the time for a long discussion.

Thanks for looking over the PR, I'll fix that.
