### ISSUE TITLE
Incorrect command line on Windows using wide strings

### ISSUE THREAD

**Issue by egorpugin** [klemens-morgenstern/boost-process#121]
See:
https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/basic_cmd.hpp#L29
https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/basic_cmd.hpp#L67

The latter does not quote program name if it has spaces.

Possible solutions:
1. Unify contents.
2. Make template function with string type argument as it's done in tons of places across STL, Boost and other libraries.

This is a sad one. :(
I tested boost process using A(scii) versions & strings before release, but now I have wide strings on windows.

**Comment by klemens-morgenstern** [comment]
Sad as in "you're sad I missed that one"? Will take care of that soon, thanks for reporting?

**Comment by egorpugin** [comment]
I'm sad that it's detected after boost release.

**Comment by egorpugin** [comment]
Wait...
Code in develop,master,boost/process,klemens-morgenstern/process is correct.
This isssue was fixed in 
https://github.com/klemens-morgenstern/boost-process/issues/97
https://github.com/boostorg/process/commit/74dd6570e3db7e25cc9320e86ff26010d667d451

What is incorrect is boost release.
https://github.com/boostorg/process/releases
1.64.0 and 1.65.0 are the same (commit 4075371).
What happened?

**Comment by klemens-morgenstern** [comment]
Just saw that on the mailing lists. I'm very sorry, I thought I kept the deadline.

**Comment by egorpugin** [comment]
I see. Closing this issue then.
