### ISSUE TITLE
POSIX, async_in, missing close of sink?

### ISSUE THREAD

**Issue by jakobandersen** [klemens-morgenstern/boost-process#124]
When piping data into a subprocess asynchronously it seems like the write end of the pipe is never closed. I think it is the subprocess who has it open. Inserting a close on the native sink in https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/async_in.hpp#L83 fixes it.
The following example should trigger the problem.
```c++
#include <boost/asio/io_service.hpp>
#include <boost/optional.hpp>
#include <boost/process.hpp>
#include <boost/process/extend.hpp>

#include <iostream>
#include <string>
#include <thread>

namespace bp = boost::process;

int main() {
	const std::string input = "Test 1\nTest 2\n";
	boost::asio::io_service ios;
	std::thread ios_thread;
	boost::optional<boost::asio::io_service::work> work;

	bp::child child(
			bp::args("cat"), bp::shell,
			bp::std_in < bp::buffer(input),
			ios
			);
	ios_thread = std::thread([&]() {
		ios.run();
	});

	child.join();
	ios_thread.join();
}
```

**Comment by sehe** [comment]
I agree with this. I keep running into it

**Comment by klemens-morgenstern** [comment]
I think I fixed that already, though it might not be in master.
