### ISSUE TITLE
Boost release 1.65.1 identical to 1.64.0

### ISSUE THREAD

**Issue by sehe** [klemens-morgenstern/boost-process#127]
It appears there as been a mistag, or a failure to update specific branches prior to release(?) meaning that the two releases are identical, and non of the post-1.64 fixes landed in 1.65.

```
git log -1 --oneline boost-1.64.0;
4075371 Merge pull request #3 from boostorg/develop
git log -1 --oneline boost-1.65.1;
4075371 Merge pull request #3 from boostorg/develop

```

**Comment by sehe** [comment]
This was already reported on the mailing list 2 months ago: http://boost.2283326.n4.nabble.com/1-65-process-Library-version-outdated-tp4698832.html

**Comment by klemens-morgenstern** [comment]
That should be alright with the update in 1.66.
