### ISSUE TITLE
Single quotes in the command line

### ISSUE THREAD

**Issue by k0lasa** [klemens-morgenstern/boost-process#128]
If I specify 
bp::child c("child -x 1 -t 'xyz 123 ttt' -k ooo", bp::std_out > stdout);
the single quotes are passed literally and the first argument to -t option is 'xyz. However double quotes seem to work fine.
I am expecting the entire string "xyz 123 ttt" passed as an argument.

**Comment by klemens-morgenstern** [comment]
This is how I implemented the library, `'` is just a regular token, at least on windows.

**Comment by klemens-morgenstern** [comment]
Is this issue still relevant? I think the double quote is the more portable way to do it, i.e. that's accepted on the posix and windows shell.

**Comment by joshedwards22** [comment]
On posix there is a difference between single and double quotes. Single quotes force everything to be literal while double quotes allow some things to be escaped. I think it is relevant.

**Comment by keith-bennett-gbg** [comment]
I don't believe that's a _POSIX_ thing. I believe that's a _shell_ thing.
