### ISSUE TITLE
Boost 1.66 windows/async_pipe.hpp compiler error on Mingw64 GCC 7.2.0

### ISSUE THREAD

**Issue by emvandijk** [klemens-morgenstern/boost-process#131]
File: `boost\process\detail\windows\async_pipe.hpp`
Function: `inline std::string make_pipe_name()`
Line: 30 
Compiler: Mingw64, GCC 7.2.0, C++14
Boost: 1.66.0

Compiler error:
`C:/msys64/mingw64/include/boost/process/detail/windows/async_pipe.hpp:30:37: error: use of deleted function 'std::atomic<long long unsigned int>::atomic(const std::atomic<long long unsigned int>&)'
     static std::atomic_size_t cnt = 0;`

To reproduce:
```cpp
#include <atomic>

int main()
{
  //static std::atomic_size_t cnt = 0;  // error
  static std::atomic_size_t cnt{0};  // OK
}
```

Relates to fix #122.

**Comment by egorpugin** [comment]
Yep, seems my bad. For some reason older gcc on travis did not show the issue as well as MSVC.

**Comment by klemens-morgenstern** [comment]
Finally merged it, so it should work now. Sorry for the delay.

**Comment by askondro** [comment]
Could this be related to this bug?

code:
```
#include <iostream>

#include <boost/process.hpp>

using namespace std;

int main()
{
    return 0;
}
```


[ 50%] Building CXX object CMakeFiles/untitled6.dir/main.cpp.obj
In file included from C:/msys64/mingw64/include/boost/process/async_pipe.hpp:20:0,
                 from C:/msys64/mingw64/include/boost/process/detail/windows/async_in.hpp:22,
                 from C:/msys64/mingw64/include/boost/process/async.hpp:49,
                 from C:/msys64/mingw64/include/boost/process.hpp:23,
                 from C:/Users/askon/OneDrive/Dokumenti/untitled6/main.cpp:3:
C:/msys64/mingw64/include/boost/process/detail/windows/async_pipe.hpp: In function 'std::__cxx11::string boost::process::detail::windows::make_pipe_name()':
C:/msys64/mingw64/include/boost/process/detail/windows/async_pipe.hpp:30:37: error: use of deleted function 'std::atomic<long long unsigned int>::atomic(const std::atomic<long long unsigned int>&)'
     static std::atomic_size_t cnt = 0;
                                     ^
In file included from C:/msys64/mingw64/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:19:0,
                 from C:/msys64/mingw64/include/boost/smart_ptr/detail/sp_counted_base.hpp:48,
                 from C:/msys64/mingw64/include/boost/smart_ptr/detail/shared_count.hpp:29,
                 from C:/msys64/mingw64/include/boost/smart_ptr/shared_ptr.hpp:28,
                 from C:/msys64/mingw64/include/boost/shared_ptr.hpp:17,
                 from C:/msys64/mingw64/include/boost/filesystem/path.hpp:29,
                 from C:/msys64/mingw64/include/boost/process/detail/traits/cmd_or_exe.hpp:14,
                 from C:/msys64/mingw64/include/boost/process/detail/basic_cmd.hpp:13,
                 from C:/msys64/mingw64/include/boost/process/args.hpp:33,
                 from C:/msys64/mingw64/include/boost/process.hpp:22,
                 from C:/Users/askon/OneDrive/Dokumenti/untitled6/main.cpp:3:
C:/msys64/mingw64/include/c++/7.3.0/atomic:783:7: note: declared here
       atomic(const atomic&) = delete;
       ^~~~~~
C:/msys64/mingw64/include/c++/7.3.0/atomic:787:17: note:   after user-defined conversion: constexpr std::atomic<long long unsigned int>::atomic(std::atomic<long long unsigned int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
                 ^~~~~~
