### ISSUE TITLE
Inconsistent behaviour in various overloaded functions/methods

### ISSUE THREAD

**Issue by markus-t314** [klemens-morgenstern/boost-process#139]
Hi Klemens,

there are currently several overloaded functions that use code duplication resulting in inconsistent behaviour (in some cases at least).

Example:
boost/process/detail/child_decl.hpp
```c++
void terminate()
{
    if (valid() && running())
        boost::process::detail::api::terminate(_child_handle);

    _terminated = true;
}

void terminate(std::error_code & ec) noexcept
{
    if (valid() && running(ec))
        boost::process::detail::api::terminate(_child_handle, ec);

    _terminated = true;
}
```
Calling terminate() might throw an error, leaving member _terminated set to false, whereas calling terminate(ec) would return the same error, but setting _terminated to true. As this is just an overload, both methods should behave the same way.

In fact, this kind of overload-behaviour can be found across several files in boost process.

My sugesstion is to get rid of all the code duplication and change the methods so something like this:
```c++
// add general throw_error function:
inline void throw_error(const std::error_code& err)
{
    if (err)
        throw process_error(err);
}

// leave the overload for error_code untouched
void terminate(std::error_code & ec) noexcept
{
    if (valid() && running(ec))
        boost::process::detail::api::terminate(_child_handle, ec);

    _terminated = true;
}
// but change the one without error_code to:
void terminate()
{
    std::error_code ec;
    terminate(ec);
    boost::process::detail::throw_error(ec);
}
```
This would result in a consistent behaviour. It is the same approach that Boost ASIO takes for such overloads.

I already did this in the pull request for wait_for_exit.hpp #138 
And I'd like to change the other occurences accordingly, for example in child_decl.hpp, is_running.hpp...

Let me know what you think of this approach.

Thanks.

**Comment by klemens-morgenstern** [comment]
I'm assuming you'd add the description to the exception as well? Then sure, that makes sense. This is actually a bug, so thanks!

**Comment by klemens-morgenstern** [comment]
Is the issue resolved?
