### ISSUE TITLE
Same io_context required for all child instances on UNIX

### ISSUE THREAD

**Issue by amerry** [klemens-morgenstern/boost-process#143]
This is an issue discussed in the comments of #99, #109 and #112. I hope you don't mind me pulling it out into a separate issue - hopefully this will be easier for people to find and track, as this applies to waiting and exit statuses in general, and not just `wait_for` and `wait_until`. I've summarised my understanding of the problem below.

When you pass an `io_context` into the constructor of a `child` instance, it installs a service on that `io_context` that will watch for `SIGCHLD` and call `::waitpid(0, ...)`, catching *any* exited child process.

If you use different `io_context` instances for difference `child` instances, those `::waitpid` calls will race (actually, I believe one will always win, based on when the signal handler services were installed). This means that some `child` instances will not receive any notification of having exited, and so won't find out about their exit status.

I think this should be solvable in the same way that ASIO solves the "global state" issue with signals - by passing the updates around the different `sigchld_service` instances.

However, this will not solve the issue for `child` instances that you don't pass any `io_context` into at all. I'm not sure how you might solve that.

**Comment by klemens-morgenstern** [comment]
It might be solvable this way. Not sure what you mean by the last paragraph though - when you call `.wait` on the child it'll go directly to `::waitpid`.

I am also not sure how the different `sigchld_service`would notify each other - do you happen to have an example for that?

**Comment by amerry** [comment]
For the second paragraph, suppose `p1` has exit status 1, and `p2` has exit status 2 (and sleeps for a second before exiting). Then the following code:

    io_service ctx;
    child c1("./p1");
    // NB: the docs are wrong: ctx.run() will not wait for the process to finish unless you use on_exit
    child c2(ctx, "./p2", bp::on_exit=[](int exit_code, std::error_code const& ec) {
                std::cout << "callback: " << exit_code << ": " << ec.message() << std::endl;
            });
    ctx.run();
    c1.wait();
    std::cout << "c1: " << c1.exit_code() << std::endl;
    std::cout << "c2: " << c2.exit_code() << std::endl;

makes the `wait()` call throw an exception:

    callback: 1: Success
    terminate called after throwing an instance of 'boost::process::process_error'
      what():  waitpid(2) failed: No child processes
    [1]    6362 abort (core dumped)  ./asio_test

The reason is that c1's process gets reaped by the `::waitpid` on the `sigchld_service` instance on `ctx`, so the `::waitpid` call in `c1.wait()` can't find the process (or any information about it).

**Comment by amerry** [comment]
For the passing around the notification, I mean having some sort of global static list of services. Then whatever service calls `::waitpid` can see if it's a PID that it knows about, and - if not - try passing it on to other services in the list. This is a bit like what ASIO's `signal_set_service` does - see `boost/asio/detail/impl/signal_set_service.ipp`.

**Comment by klemens-morgenstern** [comment]
The problem with the services would be that it would only work for other services, which would be a problem, because you might try to wait another way (e.g. using `child().wait`).

I think it's just a bug is [here](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/sigchld_service.hpp#L81), the `::waitpid` should specify the `pid` we are waiting for.

Secondly, when I call [signal](http://man7.org/linux/man-pages/man2/signal.2.html) I get the old handler. Now would it be appropriate to check if the signal is for the current `PID` and if not so call the prior one? E.g. in pseudo code:

```
struct handler
{
    pid_t pid;
    signalhandler_t old_sig = signal(*this /*wouldn't work, I know*/, SIGCHLD);

    std::function<void()> handler;
   void operator()()
   {
       auto res = ::waitpid(pid, WNOHANG);
       if (res == 0) //right, pid, has not changed state, ignore
           return;
       else if (res > 0)
           handler();
       else //wrong pid, another state changed
       {
            if ((old_sig != SIG_DFL) && (old_sig != SIG_IGN))
                  (*old_sig)(); //call the prior one
       }
   }
};
```

**Comment by amerry** [comment]
Yes, passing the PID you are interested in to `::waitpid` should produce the correct behaviour. If you iterate through `_receivers` in `sigchld_service::_handle_signal` and call `::waitpid` for each of them, and erase the successful ones (and, I guess, the ones that fail because the process has been reaped?), that should work.

If you're manually installing signal handlers, that might be appropriate, I'm not sure. But:

* I think you can get one signal for multiple children exiting
* You shouldn't need to do this to make the normal blocking `::waitpid` work
* I'm not sure exactly what calling the default handler does (although it's probably fine)
* If you use `asio::signal_set`, the only constraint is that the user doesn't go around installing signal handlers for `SIGCHLD` (at least, not without chaining it in the way you suggest).

**Comment by amerry** [comment]
I can probably throw together an MR this afternoon.

**Comment by klemens-morgenstern** [comment]
I was thinking about the latter, i.e. a custom SIGCHLD handler. If this library gets used in another context (e.g. with a framework like Qt that provides it's own process library) that might be a necessary case to support. Not the current issue, but since that would be a rework we might as well consider that now. I'd ignore the `SIG_DFL` since I can check if the prior signal points there.

**Comment by amerry** [comment]
For now, I'd rather do the simple fix of passing a sensible value to `::waitpid`, continuing to use `asio::signal_set`. Otherwise we'd need to replicate `signal_set`'s way of dealing with multiple `io_context` instances.
