### ISSUE TITLE
multi-step input to a shell process

### ISSUE THREAD

**Issue by rockonedege** [klemens-morgenstern/boost-process#15]
Not sure if this qualifies as an issue or feature request, but you are apparently an expert here. I'd ask it anyway.
Under Windows, I execute cmd.exe(the shell), and them inside it, I could run built-in command(e.g. set), programs and batch scripts in a row and mix them  all in the **same shell process**.

Can I do this with boost process?

I am asking for this because the scripts and programs I am running in the same shell window relies on previous one changes to the system environment. If I run then one by one with,  say,  std::system(), a new process is created for each run, and the scripts/programs but the very first one would fail due to wrong/missing environment variables. 

I can not change the scripts/programs, except for wrapping them in a certain way.

I read the documentation,  it looks I could create a console process and use [WriteConsoleInput()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687403(v=vs.85).aspx)  to append the scripts/programs, but it seems to be overkill. Does boost.process offer a simpler solution? The key is to share the same environment for my immediate usage.

**Comment by klemens-morgenstern** [comment]
Not in the way you are describing. You can execute scripts through the console, but that only works for a single program. You can modify the environment in the current process via `boost::this_process::environment` but you cannot get a changed environment from the child or change it after it launched.

However, I did not try this, but maybe this works:

```cpp
namespace bp = boost::process;

bp::opstream os;
bp::child cmd(bp::shell(), bp::std_in < os);

os << "script1" << endl;
os << "script2" << endl;
```


I think this would indeed be an overkill for this library; there are plenty of things other people would like to do with processes like having a DSEL etc. I think this would be better to write a seperate library for this, which maybe build ontop of boost.process.
