### ISSUE TITLE
On Linux spawning processes from multiple threads causes child process not to exit due to leaking file descriptors

### ISSUE THREAD

**Issue by sogartar** [klemens-morgenstern/boost-process#153]
I have this simple test code.

```cpp
#include <thread>
#include <iostream>
#include <vector>
#include <memory>
#include <boost/process.hpp>
#include <boost/test/unit_test.hpp>

static void boostProcessCat() {
  std::shared_ptr<boost::process::opstream> outPipe = std::make_shared<boost::process::opstream>();
  boost::process::child catProcess("cat -", boost::process::std_in < *outPipe);

  // Close pipe
  outPipe = nullptr;

  catProcess.wait();
  BOOST_CHECK_EQUAL(catProcess.exit_code(), 0);
}

BOOST_AUTO_TEST_CASE(boostProcessCatTest) {
  boostProcessCat();
}

BOOST_AUTO_TEST_CASE(boostProcessCatSimultaneousTest) {
  int nThreads = 1000;

  std::vector<std::thread> threads;
  threads.reserve(nThreads);

  for (int i = 0; i < nThreads; ++i) {
    threads.emplace_back(boostProcessCat);
  }

  for (int i = 0; i < nThreads; ++i) {
    if (threads[i].joinable()) {
      threads[i].join();
    }
  }
}
```

The function `boostProcessCat` opens `cat`, then closes its input pipe. Afterwards we wait for `cat` to exit. `cat` should exit because we closed its stdin pipe.
The test `boostProcessCatSimultaneousTest` spawns 1000 threads. Each of them just to call `boostProcessCat`. In this scenario the `cat` never exits. Note that calling `boostProcessCat` just once is OK.

The reason I decided to try Boost.Process is to circumvent this very same problem that I also encountered when trying to write a Linux process spawn function that opens pipes to child's stdio.
The problem is that there are leaking file descriptors across the call to some of the `exec` family functions. This is caused when two threads get to the point of `fork` at the same time. The Linux pipes were probably created without `FD_CLOEXEC` being set. This is of course desirable because we want the pipes to be open in the child process. After `fork` both child processes would have these pipes inherited, so they would leak.
Because this is a general purpose library, what needs to be done after `fork` is to close all other file descriptors, except those that are associated with the pipes we want. Somewhere I read that the Java virtual machine does it like that. I also can't see any other way of doing it. There is no POSIX function to get all file descriptors of a process. On Linux you can get them from `/proc/<pid>/fd`. I have read that this is not portable across all Linux variants.
If you are sure that in the parent process the only usage of `fork` is to afterwards `exec` another file, there is another option. Create the pipes with `FD_CLOEXEC` set. Then after the fork unset the flag before doing `exec`. Then only the pipe you want "leaks". This of course assumes also that in the parent process there are no other file descriptors open without `FD_CLOEXEC`. When I tried to do that I got some very nasty memory corruptions in the parent. When running with Valgrind could not reproduce the problem, no invalid memory reads/writes. Welcome to fork&threads hell :)

**Comment by klemens-morgenstern** [comment]
I recently added a bugfix, because I missed some closing during the initialization, which would not be part of the boost.process released in 1.66 - have you tried the current master or 1.66?

The `FD_CLOEXEC` is also difficult, since you might want to keep a pipe alive after one process - it is however easy to add a custom initializer to set the flag for you, you can find the documentation [here](http://www.boost.org/doc/libs/1_66_0/doc/html/boost_process/extend.html) or [here](http://www.boost.org/doc/libs/1_66_0/doc/html/boost/process/extend/posix_executor.html)

Hope that helps.

**Comment by sogartar** [comment]
I tried the current develop branch or `8e8d36772e0b9ed33c5b99262c58b0d18a9de887` with boost 1.66.

**Comment by keith-bennett-gbg** [comment]
> There is no POSIX function to get all file descriptors of a process.

There isn't a single function to enumerate descriptors in your process. However, you can retrieve your process's file descriptor limit using `getrlimit(RLIMIT_NOFILE, &rlimit)`. You can then loop `for (fd = 0; fd < rlimit.rlim_cur; ++fd)` calling `fcntl(fd, F_GETFD)`. That will tell you which file descriptor numbers are open in your process. It'd then be up to you to associate which ones you want to keep or close prior to `exec()`.

Note that `getrlimit()` is not specifically mentioned in `signal-safety(7)` so you would want to avoid using it between `fork()` and `exec()`. However, a child created via `fork()` inherits its parent's limits so it should be fine to retrieve the values prior to forking.

**Comment by sogartar** [comment]
I spend a little more time on the problem and I got a better understanding of the file descriptor functionality.
I think you should use `pipe2` with `O_CLOEXEC` when creating the pipes. Also `dup2` does not copy file descriptor flags. Then you would not have leaking file descriptors across `exec*` calls. I feel this should be the default behavior when piping stdio of the child process.
Another thing to note about the test case I provided is that it turns out `BOOST_CHECK_*` are not thread safe. They would ruin your stack.
Here is a fixed version.
```
#include <thread>
#include <iostream>
#include <vector>
#include <memory>
#include <stdexcept>
#include <boost/process.hpp>
#include <boost/test/unit_test.hpp>
#include <boost/format.hpp>

static void boostProcessCat() {
  std::shared_ptr<boost::process::opstream> outPipe = std::make_shared<boost::process::opstream>();
  boost::process::child catProcess("cat -", boost::process::std_in < *outPipe);

  // Close pipe
  outPipe = nullptr;

  catProcess.wait();
  if (catProcess.exit_code()) {
    throw std::runtime_error((boost::format("\"cat -\" failed with exit code %d") % catProcess.exit_code()).str());
  }
}

BOOST_AUTO_TEST_CASE(boostProcessCatTest) {
  boostProcessCat();
}

BOOST_AUTO_TEST_CASE(boostProcessCatSimultaneousTest) {
  int nThreads = 1000;

  std::vector<std::thread> threads;
  threads.reserve(nThreads);

  for (int i = 0; i < nThreads; ++i) {
    threads.emplace_back(boostProcessCat);
  }

  for (int i = 0; i < nThreads; ++i) {
    if (threads[i].joinable()) {
      threads[i].join();
    }
  }
}
```

**Comment by jbwdevries** [comment]
I've had to deal with this issue with Boost Process 0.5 too. There I could use my own create_pipe method to work around this issue. With the new Boost Process this doesn't seem as easy. Any news on this being merged?

**Comment by klemens-morgenstern** [comment]
@jbwdevries no progress currently, because it is a hard problem to be solved, because the app using boost.process may have way more file descriptors open.

**Comment by jbwdevries** [comment]
@klemens-morgenstern I understand that. But ATM I can close all file descriptors in the various Boost libraries[1] except those created by Boost Process. It would already be a help if we could close these too. It would be nice to have a complete solution, but this step helps a lot.

[1] Even if via a little workaround sometimes

**Comment by klemens-morgenstern** [comment]
Which file-descriptors are you talking about? The self-pipe I use for error-handling? That'll be fixed soon.

**Comment by jbwdevries** [comment]
As in the PR, pipes created by Boost Process should be as much CLOEXEC as possible. This is mostly because if you spawn two or more processes, pipes from the first will leak into the second. That's the problem I ran into when using Boost Process 0.5.

**Comment by FatihBAKIR** [comment]
Is there at least any work around to this problem? I'm on Boost 1.69, and my, long running, program runs out of descriptors and just terminates routinely.

**Comment by klemens-morgenstern** [comment]
It is fixed in the current develop branch. If you replace the posix executor with pull in https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/executor.hpp

You can either drop that into your installation or use `ignore_error` or `vfork`, which will both avoid using the self-pipe for errors.

**Comment by jonmcclung** [comment]
Was this included in Boost 1.70 or will we have to wait until 1.71?

**Comment by jonmcclung** [comment]
> It is fixed in the current develop branch. If you replace the posix executor with pull in https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/executor.hpp
> 
> You can either drop that into your installation or use `ignore_error` or `vfork`, which will both avoid using the self-pipe for errors.

Was this fix included in Boost 1.70 or will we have to wait for Boost 1.71 if we want to avoid manually replacing headers?

**Comment by evetsso** [comment]
This appears to still be a problem in the current develop branch.  I'm still observing hangs with the test code in the initial issue description.  `pipe2` with `O_CLOEXEC` appears to solve the problem for me.

Another potential workaround is to add a mutex around the creation of pipes (e.g. `boost::process::ipstream` and boost::process::opstream`) and calling `fork` (i.e. when the boost::process::child object is constructed) - those would need to be together in a critical section to prevent a `fork` happening in between those two operations.  Depending on what else is going on inside your process, this workaround might not be feasible.

Yet another possibility (if boost::process cannot or will not use `pipe2`) would be to make your own basic_pipe class, mimicking `boost/process/detail/posix/basic_pipe.hpp` and have it call `pipe2` instead of `pipe`.  That's probably a lot easier said than done.

**Comment by evetsso** [comment]
Hah.  Ok, another workaround that works for me is to (ab)use the `FILE*` overloads for `boost::process::std_in` and `boost::process::std_out`, e.g.:
```c++
  int stdin_fds[2];
  pipe2(stdin_fds, O_CLOEXEC);
  FILE* child_stdin_read  = fdopen(stdin_fds[0], "r");
  FILE* child_stdin_write = fdopen(stdin_fds[1], "w");

  int stdout_fds[2];
  pipe2(stdout_fds, O_CLOEXEC);
  FILE* child_stdout_read  = fdopen(stdout_fds[0], "r");
  FILE* child_stdout_write = fdopen(stdout_fds[1], "w");

  boost::process::child catProcess("/bin/cat", boost::process::std_in < child_stdin_read);

  //
  //  Now, you could fwrite to child_stdin_write, to provide data to child on stdin
  //

  // close handles
  fclose(child_stdin_write);
  fclose(child_stdin_read);
  fclose(child_stdout_write);

  // 
  // Here, you could fread stdout from child_stdout_read
  //

  // close last handle
  fclose(child_stdout_read);

  catProcess.wait();
```
Proper error handling and async reading/writing of the data are left as an exercise for the reader.  :)

**Comment by klemens-morgenstern** [comment]
In V1 this would be fixed with limit_handles, in V2 the handles will be closed automatically.

I am closing this issue because I'll archive this repository. Please reopen if you see the need over to boostorg/process.
