### ISSUE TITLE
[Windows][boost 1.66.0] Visual Studio 2017 linker error boost filesystem

### ISSUE THREAD

**Issue by 7085** [klemens-morgenstern/boost-process#156]
I try to use boost::process header only. In Visual Studio (latest version) I get the linker error that it cannot find "libboost_filesystem-vc141-mt-gd-x32-1_66.lib". But why does it want to link to the filesystem lib?

For testing I created a "Console Project" and used the following code:
```cpp
#include <cstdio>
#include <chrono>
#include <boost/process.hpp>

#define WORKER_EXE ("test.exe")

int main()
{
	namespace bp = boost::process;
	bp::child *testProcess;

	std::error_code error;
	testProcess = new bp::child(WORKER_EXE, error);

	if (!testProcess->wait_for(std::chrono::seconds(3))) {
		testProcess->terminate();
	}
	delete testProcess;
	return 0;
}
```
In the settings I disabled the sdl checks for testing as well as using precompiled headers.

So does it have a required dependency on the boost filesystem lib?
I am wondering because this is mentioned nowhere (or at least I could not find anything related).

**Comment by klemens-morgenstern** [comment]
It shouldn't have unless you use boost::filesystem. Will check.

**Comment by thesmartwon** [comment]
Just this causes it to happen:
```
#include <boost/process.hpp
int main() { }
```
Same result with Boost 1.65_1 and 1.64_0. I didn't try earlier versions since I don't think they have the process module. [bcp](http://www.boost.org/doc/libs/1_66_0/tools/bcp/doc/html/index.html) might help narrow down the dep ([usage](https://stackoverflow.com/questions/28182598/how-to-extract-boostfilesystem-using-bcp), [cool graph](https://steveire.wordpress.com/2016/08/21/boost-dependencies-and-bcp/)). It's fine if it requires the lib to be built, I'd just like some mention on the [doc page.](http://www.boost.org/doc/libs/1_65_1/doc/html/process.html)

**Comment by klemens-morgenstern** [comment]
Ah! Yes, it is (or might be), the filesystem headers will automatically try to link with the `#pragma` when included, which you can disable that by defining `BOOST_ALL_NO_LIB`. Didn't think of that.

**Comment by thesmartwon** [comment]
Well, that flag only leads to two more linker errors with unresolved external symbols:
```
class boost::system::error_category const & __cdecl boost::system::system_category(void)
referenced in function class boost::system::error_category const & __cdecl boost::asio::error::get_system_category(void)

class boost::system::error_category const & __cdecl boost::system::generic_category(void)
referenced in function public: virtual bool __cdecl boost::system::error_category::std_category::equivalent(class std::error_code const &,int) const
```

By default boost is using _WIN32_WINNT=0x0501. Compiling 64 and 32 bit does the same thing.

**Comment by klemens-morgenstern** [comment]
Alright, that seems more fishy, I'll check it out. THanks for reporting.

**Comment by 7085** [comment]
Yes tried `BOOST_ALL_NO_LIB` before, it does not work.
Maybe you can check boost::interprocess, they have an option to define `BOOST_DATE_TIME_NO_LIB` which prevents msvc of linking this lib, which I can confirm that it works.
So maybe you find an uncomplicated solution there.

**Comment by klemens-morgenstern** [comment]
Sry I missed it back then, but thise error handling is pulled in by boost.asio which uses these error_codes. And this is included through `process/async.hpp` and `process/async_system.hpp` which `process.hpp` includes. If you don't need asio and include seperately the modules you need it should work.

**Comment by 7085** [comment]
Does not work for me.
In the example I would need `child.hpp` but then `child.hpp -> execute_impl.hpp -> basic_cmd.hpp -> filesystem/path.hpp` or `child.hpp -> execute_impl.hpp -> basic_cmd.hpp -> shell.hpp -> shell_path.hpp ->filesystem/path.hpp` will get included.

I get the following unresolved symbols with that:
```
1>ConsoleApplication2.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &,class std::codecvt<wchar_t,char,struct _Mbstatet> const &)" (?convert@path_traits@filesystem@boost@@YAXPBD0AAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@ABV?$codecvt@_WDU_Mbstatet@@@5@@Z)" in Funktion ""void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &)" (?convert@path_traits@filesystem@boost@@YAXPBD0AAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)".
1>ConsoleApplication2.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""void __cdecl boost::filesystem::path_traits::convert(wchar_t const *,wchar_t const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::codecvt<wchar_t,char,struct _Mbstatet> const &)" (?convert@path_traits@filesystem@boost@@YAXPB_W0AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$codecvt@_WDU_Mbstatet@@@5@@Z)" in Funktion ""public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __thiscall boost::filesystem::path::string(class std::codecvt<wchar_t,char,struct _Mbstatet> const &)const " (?string@path@filesystem@boost@@QBE?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$codecvt@_WDU_Mbstatet@@@5@@Z)".
1>ConsoleApplication2.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""public: class boost::filesystem::path & __thiscall boost::filesystem::path::operator/=(class boost::filesystem::path const &)" (??_0path@filesystem@boost@@QAEAAV012@ABV012@@Z)" in Funktion ""class boost::filesystem::path __cdecl boost::filesystem::operator/(class boost::filesystem::path const &,class boost::filesystem::path const &)" (??Kfilesystem@boost@@YA?AVpath@01@ABV201@0@Z)".
1>ConsoleApplication2.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""public: static class std::codecvt<wchar_t,char,struct _Mbstatet> const & __cdecl boost::filesystem::path::codecvt(void)" (?codecvt@path@filesystem@boost@@SAABV?$codecvt@_WDU_Mbstatet@@@std@@XZ)" in Funktion ""void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &)" (?convert@path_traits@filesystem@boost@@YAXPBD0AAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)".
```

**Comment by JCYang** [comment]
I'm another user who encounter this problem.
The very same codes builds successfully without links to boost_filesystem on linux.
What make such differences?

**Comment by klemens-morgenstern** [comment]
That is because the `#pragma link` that is only used on windows unless you define `BOOST_ALL_NO_LIB` and because `boost.filesystem` only needs to do the char-conversions you get the error for on windows.

**Comment by JCYang** [comment]
Too busy recently to help investigating this issue.
Just some suggestions
BOOST_FILESYSTEM_NO_LIB can reveal what's being linked.
Then dumpbin can help located the source of references to the symbols, and the call chain.
Just glance, it seems that the filesystem::path internally store path in strings with wchar_t on windows, and consequently required some overloaded of convert and codecvt which is not available in the header.
Just my 2 cents. Hope it helps

**Comment by klemens-morgenstern** [comment]
Closing because it it a `boost::filesstem` issue, so not of boost.process.
