### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by mjcaisse** [klemens-morgenstern/boost-process#16]
It doesn't seem like the library supports OSX. Is there a plan for this?

**Comment by klemens-morgenstern** [comment]
Isn't OSX posix based? 

While until now only testing on linux, I tried to adhere to the posix-standard, not the linux implementation. 
That is why a few things are optional, such as `vfork`. So if there is either something not posix-compliant in the library, it would technically be a bug, If it's a OSX specific detail, I'd like to add workarounds for that.

**Comment by mjcaisse** [comment]
Hi -
We are scrambling around trying to hit some deadlines. I have this on my list to get back to you. I suspect just trying to run the tests will fail. There are missing includes for one.

Meanwhile, I've backed up to the tried and true 0.5 version. What you have looks promising so I want to get back to providing more information.

**Comment by klemens-morgenstern** [comment]
Perfect. I'll see if I find a way to test this on MacOS. And I guess once that works, some Solaris user will complain.

**Comment by klemens-morgenstern** [comment]
I just looked over the include and compared them to the [open group documentation](http://pubs.opengroup.org/).

This had only two issues:

## <sysexits.h>

This is for some reason included and not used (I think)

## <wait.h>

I seem to have missed this, it should be `<sys/wait.h>` not just `<wait.h>`

Are there any more include issues you get?

**Comment by klemens-morgenstern** [comment]
So, I changed the includes to be posix-conforming, i.e. remove `sysexits.h` and changes `wait.h` to `sys/wait.h`. As far as I can see, that makes at least the includes posix-conforming. If you by any chance get a opportunity to test that, the commit is 4d679fb2565634057524035feb778abf0e6f8eef.

**Comment by klemens-morgenstern** [comment]
@mjcaisse Any news? Btw: the formal review is next week, so you'd help me out a great deal if you test it on OSX.

**Comment by klemens-morgenstern** [comment]
See PR #46.

**Comment by klemens-morgenstern** [comment]
Based on PR  #46 I tried to build a fix in 663fc69691afe2d5896ae354ef1069912c2beb5b. , but I can't test it. If you find the time, I'd be very grateful if you take a look.

**Comment by klemens-morgenstern** [comment]
I'm assuming it is supported now as of 2a7f5bb66fbfddde808910a2003b7857078ffb5f. Feel free to reopen this issue if anything doesn't work properly on OSX.

**Comment by avaskoog** [comment]
I may be doing something wrong, but it doesn't work for me at all. I've followed all the examples, and everything compiles and runs (tho I had to add an #include for boost::filesystem's `operations.hpp` into boost::process's `operations.hpp` to resolve a missing reference), and exit status is fine.

The weird thing is that even if I try to run programs that don't exist, I still get a process ID for the child.

Tried simple things like `touch`ing files in the home directory using the full path, but even that didn't work, which of course it does if I try to run the exact same command in the terminal.

Essentially what I'm doing is this:

```
boost::process::context ctx;
ctx.work_directory = boost::filesystem::current_path().string();
ctx.environment = boost::process::self::get_environment();

std::vector<std::string> args;
args.emplace_back("xcode4");

auto c(boost::process::launch("premake5"s, args, ctx));
```

I have no pointers. It's just... silently failing.

**Comment by klemens-morgenstern** [comment]
@avaskoog I know what you're doing wrong, you're using an ancient version of `boost.process`.

**Comment by avaskoog** [comment]
Now that's embarrassing. Got the latest from this repo and there we go. Can confirm it works like a charm on Mac. So is it using NSTask now, or still the general POSIX thing?

**Comment by klemens-morgenstern** [comment]
Pure posix, just a few workarounds for OSX.
