### ISSUE TITLE
async_system exit handler not called?

### ISSUE THREAD

**Issue by biosmanager** [klemens-morgenstern/boost-process#160]
I'm using async_system to call an external script. To my understanding the associated exit handler should be called, when the launched process/script exits. But it doesn't.
```
boost::asio::io_service ios;
boost::process::async_system(ios, [&](boost::system::error_code error, int i) {
    std::cout << "in exit handler" << std::endl;
}, scriptPath);
```
The cout statement is never executed. The script itself launches fine because it produces some output files.  
Am I doing something wrong or is this a bug in the library?

**Comment by klemens-morgenstern** [comment]
After `async_system`, that should solve your problem - and it shouldn't actually execute the script to begin with. If you don't need all the async-stuff, you might also just want to use `boost::process::system`.

**Comment by biosmanager** [comment]
Strange. Because the script is executed, even without `ios.run()`. I need the async stuff because the script may run for a long time.

**Comment by klemens-morgenstern** [comment]
Ah, you're right, the `async_system` directly spawns the child and then adds the exit handler to the queue of the `io_service`. Nevermind that then. Does calling `run` solve the issue?

**Comment by biosmanager** [comment]
Nope. It blocks until the script is finished. This is not suitable for my scenario because the session where I launch the script gets killed after a short timeout when it doesn't send an alive signal.

**Comment by klemens-morgenstern** [comment]
Of course it blocks, that's what the `run` function does. `boost:.asio` allows you to do several things asynchronously, but will still need at least one thread.
So is the exit-handler called when you call `ios.run()` or not?

**Comment by biosmanager** [comment]
Yes, it is. But why isn't it called without `run()`?
I simply need a mechanism to do something after the script has executed. But I don't want my GUI to block while it does. Sorry if this question seems stupid but `async_system` seems like it could do this.

**Comment by klemens-morgenstern** [comment]
Well that's the way `asio` works, there is no generic enough way to provide a callback for posix and windows. Thus the io_service can do several things at onec, but needs a thread to run on.

What you might want to do is to create a `child` and poll the state through `exited`. Other than that, it doesn't seem to be an issue with the library, which behaves as specified. So I'd close that now, if you need some more help you can also E-Mail me.

**Comment by biosmanager** [comment]
Excuse the question but isn't the exit handler functionality completely useless then?
If I need to call `run()` and it becomes blocking, why would I need `async_system`?
I don't see why you can specify an exit handler if it is never called.

**Comment by klemens-morgenstern** [comment]
Not if you do a bunch of asynchronous I/O wit `boost::asio`. The call of run maybe blocking but you can have a number of calls of `async_system` etc. with one `io_service`. So instead of launching on thread per process using `system` you have on thread for all of them using `io_service.run()` . Btw. another way to achieve that is by frequently calling `io_service::poll_one` from your Gui main event loop.
