### ISSUE TITLE
Example showing asynchronous read/write between 2 chained child processes

### ISSUE THREAD

**Issue by cypherpu** [klemens-morgenstern/boost-process#162]
I am trying to understand how to chain together 2 processes aynchronously. This needs to be done asynchronously because I am working with large files, and I need to track the number of chars output by the two pipes.

In the attached program, bzip_to_file_pipe.async_read_some() never reads any data, even though a async_read_some is queued. How can I remedy this? A working example in the docs would be beneficial.

`
	
	#define BOOST_ASIO_ENABLE_HANDLER_TRACKING 1
	
	#include <boost/asio.hpp>
	#include <boost/asio/high_resolution_timer.hpp>
	#include <boost/process.hpp>
	#include <boost/process/async.hpp>
	#include <iostream>
	#include <fstream>
	#include <functional>
	
	namespace bp = boost::process;
	using boost::system::error_code;
	using namespace std::chrono_literals;
	
	using Loop = std::function<void()>;
	using Buffer = std::array<char, 1024>;
	
	int main() {
		boost::asio::io_service svc;
		bp::async_pipe file_to_gzip_pipe{svc}, gzip_to_bzip_pipe{svc}, bzip_to_file_pipe{svc};
	
		auto gzip_exit = [](int code, std::error_code ec) {
				std::cout << "gzip exited " << code << " (" << ec.message() << ")\n";
			};
	
		auto bzip2_exit = [](int code, std::error_code ec) {
				std::cout << "bzip2 exited " << code << " (" << ec.message() << ")\n";
			};
	
		bp::child process_gzip("/usr/bin/gzip", "-c", bp::std_in < file_to_gzip_pipe, bp::std_out > gzip_to_bzip_pipe, svc, bp::on_exit(gzip_exit));
		bp::child process_bzip2("/usr/bin/bzip2", "-c", bp::std_in < gzip_to_bzip_pipe, bp::std_out > bzip_to_file_pipe, svc, bp::on_exit(bzip2_exit));
	
		std::ifstream ifs("src/ProcessPipe2.cpp");
	
		Buffer file_to_gzip_buffer;
		Loop file_to_gzip_loop;
		file_to_gzip_loop = [&] {
			if (!ifs.good())
			{
				file_to_gzip_pipe.close();
				std::cout << "Read file, ..........: closed stdin\n";
				return;
			}
	
			ifs.read(file_to_gzip_buffer.data(), file_to_gzip_buffer.size());
			std::cout << "Read file, ..........\n";
			boost::asio::async_write(file_to_gzip_pipe, boost::asio::buffer(file_to_gzip_buffer.data(), ifs.gcount()),
				[&](error_code ec, size_t transferred) {
					std::cout << "........., write gzip: " << ec.message() << " sent " << transferred << " bytes\n";
					if (!ec) {
						file_to_gzip_loop(); // continue writing
					}
				});
		};
	
		std::ofstream ofs("src/ProcessPipe2.gz.bzip2");
	
		Buffer bzip_to_file_buffer;
		Loop bzip_to_file_loop;
		bzip_to_file_loop = [&] {
			bzip_to_file_pipe.async_read_some(boost::asio::buffer(bzip_to_file_buffer),
				[&](error_code ec, size_t transferred) {
					std::cout << "Read bzip, write file: " << ec.message() << " got " << transferred << " bytes\n";
					ofs << std::string(bzip_to_file_buffer.data(),transferred);
					if (!ec)
						bzip_to_file_loop(); // continue reading
					else
						bzip_to_file_pipe.async_close();
				});
		};
	
		file_to_gzip_loop();
		bzip_to_file_loop();
	
		svc.run();
	}

`

**Comment by klemens-morgenstern** [comment]
The passing of an async_pipe to `std_in` / `std_out` will close the source/sink, because that's the normal way of hanling things. I.e.:

```cpp
bp::ipstream is;
bp::child c("ls", bo::std_out> is);
while (is.good())
   do_something(is);
```

Now you have to close the sink of `is` on the side of ther father process so the eof appears.

**Comment by klemens-morgenstern** [comment]
Regarding your example, you don't need an async-pipe in-between the processes and you don't need a filestream - I'd let all that be done by the OS. Here's how I'd write it:

```cpp
bp::pipe p; //interprocess pipe
// we spawn gzip, since we know it will exit automatically and we know when by the pipe being closed
bp::spawn("/usr/bin/gzip", "-c", 
                 bp::std_in < "src/ProcessPipe2.cpp, //read directly from the file, i.e. let the OS do that
                 bp::std_out > bp::pipe(p)); //explicitly copy the pipe, so it can close the source
//and we'll do the next step sync, you of course can do it another way...
int res = bp::system("/usr/bin/bzip2", "-c", bp::std_in < p /*no need to copy it here */,
                 bp::std_out > ""src/ProcessPipe2.gz.bzip2" /* directly to the file */);

std::cout << "Zipping gave the result " << res << std::endl;
```

Hope that helps, let me know if it works.
