### ISSUE TITLE
Handle C++17 std::filesystem::path

### ISSUE THREAD

**Issue by egorpugin** [klemens-morgenstern/boost-process#164]
Gcc 8.1, VS15.7 (2017) are released with std::filesystem support.
Boost::process must learn how to handle them in all places where it could handle boost::filesystem.
`bp::search_path(std::filesystem::path("b2"));`

**Comment by klemens-morgenstern** [comment]
Boost.process is still a C++11 library and should remain backwards-compatible. I'd accept any PR that doesn't break said compatibility though.

**Comment by egorpugin** [comment]
I'm thinking about how it's possible to make both boost::fs and std::fs co-exist in the code.
I asked on the boost ML, we'll see if there's any good ideas.

**Comment by barcharcraz** [comment]
Looks like Boost::DLL added BOOST_DLL_USE_STD_FS I'm not sure what the compat limitations are with that though.

**Comment by klemens-morgenstern** [comment]
Done, #define BOOST_PROCESS_USE_STD_FS which will come with the next release.
