### ISSUE TITLE
Error on asyncronous i/o tutorial

### ISSUE THREAD

**Issue by tiagobonetti** [klemens-morgenstern/boost-process#169]
on the second example of the [Asynchronous I/O tutorial](https://www.boost.org/doc/libs/1_66_0/doc/html/boost_process/tutorial.html#boost_process.tutorial.async_io): 

```
std::vector<char> buf;

bp::child c(bp::search_path("g++"), "main.cpp", bp::std_out > boost::asio::buffer(buf), ios);
```
This code will result in reading nothing because the buffer has zero space available.

It took me an hour to notice what I was doing wrong.

**Comment by klemens-morgenstern** [comment]
Really sorry about that, fixed it. Thank you for reporting
