### ISSUE TITLE
system(async_property) does not return the correct exit_code

### ISSUE THREAD

**Issue by krwalker** [klemens-morgenstern/boost-process#178]
When using `boost::process::system(async_property, ...no_io_service...)`, the correct exit code is not returned:
```cpp
  std::array< char, 1024 > buffer;
  const int buffer_exit_code = boost::process::system(command, boost::process::std_out > boost::asio::buffer(buffer));
  BOOST_CHECK_EQUAL(buffer_exit_code, 0); // <--- FAILS
```

Boost: 1.65.1 with 74814e46c1614850a8e447fd689c21cf82f36ceb from #90
OS: Windows 10 Pro (version 1803, build 17134.285)
IDE/Compiler: Visual Studio 2017 (v15.8.4) / cl.exe v19.15.26729.0

A nearly-complete test-case is attached along with the sanitized output:
[boost-process-test.txt](https://github.com/klemens-morgenstern/boost-process/files/2398559/boost-process-test.txt)
[boost-process-test-output.txt](https://github.com/klemens-morgenstern/boost-process/files/2398557/boost-process-test-output.txt)

**Comment by klemens-morgenstern** [comment]
Thanks for the report `259` is the return code when the process is still running. 
Does it solve the issue when you add `c.wait();` before the return [here](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/system.hpp#L88) ?

**Comment by krwalker** [comment]
Adding c.wait() before the return solves the issue in the attached test-case.
