### ISSUE TITLE
std::system versus bp::system

### ISSUE THREAD

**Issue by fkonvick** [klemens-morgenstern/boost-process#182]
Hi,

The docs led me to believing that bp::system works as a replacement of std::system.  However, the call seems to run the command in a different way:  while
`  std::system("echo hello && echo world");`
works, bp::system does not (at best it prints `hello && echo world`).  The following does work though:
`  bp::system(bp::shell().native() + " -c \"echo hello && echo world\"");`
But this is platform&shell specific, and requires that non-trivial transformation is done on the shell script to be run.
I was actually trying to use bp::child so that I can capture the shell script stdout and stderr, which does work but requires the same trick as above.

Thanks,
Filip

**Comment by klemens-morgenstern** [comment]
`std::system` is doing a lot of stuff and I think `bp::system` was a bad idea. In v2 it's `execute` which will make it much more obvious.

I am closing the issue, because I'll move issued to `boostorg/process`.
