### ISSUE TITLE
async on_exit and attached process

### ISSUE THREAD

**Issue by sbelsky** [klemens-morgenstern/boost-process#183]
is it possible to asyncroniusly wait a child, created by "pid" constructor?

all async examples consist somethink like:
`bp::child( ... , ios, bp::on_exit( [](int, const std::error_code&) { bla bla }), ... );`

but what if i know PID of the ready process and want to do the following:
`bp::child(PID, ... , ios, bp::on_exit( [](int, const std::error_code&) { }), ... );`

**Comment by klemens-morgenstern** [comment]
That is currently not possible. You can use adio::signal_set with SIGCHLD instead, though not a great solution.

**Comment by klemens-morgenstern** [comment]
Why might be possible, would be a pure `boost::asio` implementation, like this.

```cpp
auto async_wait(PID, io_context, [](int, boost::system::error_code){});
//OR
auto async_wait(child, io_context, [](int, boost::system::error_code){});
```

Would that solve your issue? I can't guarantee I will add this, since it might introduce race conditions, but worth to think about.

**Comment by klemens-morgenstern** [comment]
I implemented the latter in v2:

```cpp
boost::process::v2::process proc(ctx, pid);
proc.async_wait();
```
