### ISSUE TITLE
Recover POSIX exit status

### ISSUE THREAD

**Issue by jasonmccampbell** [klemens-morgenstern/boost-process#184]
Thanks for this package -- it's nice to finally have all of this abstracted and standard. We are using it on POSIX systems and want to recover the signal number which caused the process to exit should something go wrong. We have local changes to do it, but my preference is to make it standard if possible.

Because child::exit_code() calls eval_exit_status() the result is ambiguous, both the exit code and signal number are in the first byte. If we had access to the raw exit code, that would let us figure it out, but wouldn't be portable with Windows.

One possibility is to add a method 'signaled' which turns WIFSIGNALED(code) on POSIX systems and perhaps 'false' always on Windows systems. This would provide the information callers need to interpret exit_code(). 

Does this make sense or is there another option? I'm happy to provide a PR if there is a reasonable solution.

**Comment by klemens-morgenstern** [comment]
The problem is rather, that windows has two ways to "signal" a process as well and I didn't implement them because they're not portable. If you have an idea though, I would like to hear it.  Does using `waitpid` manually not work for you? I.e.

```cpp
child c(...);

int status;
waitpid(c.native_handle(), &status, 0);

//eval status
c.detach();
```

or something similar with `asio::signal_set` if you need the async version.

**Comment by klemens-morgenstern** [comment]
That's not a bad idea. And then you have an exit-code and native-exit-code function. That would also solve the issue you would have with async behavior.

**Comment by jasonmccampbell** [comment]
I submitted PR #186 with the changes we are using locally to access the native exit code in case you are interested in them. Please let me know if there is anything else you would like me to include.

**Comment by klemens-morgenstern** [comment]
Looks good, thanks! I am currently struggling a bit with OSX, so it might take a bit longer until it makes it into master, sadly.
