### ISSUE TITLE
Feature Request: attach

### ISSUE THREAD

**Issue by jpvienneau** [klemens-morgenstern/boost-process#19]
Is it possible to attach to an exiting process for monitoring purposes and perhaps even to send a terminate signal?

Thanks for working on this, BTW. It is a great library to have. Even if it cannot be everything to everybody.

**Comment by klemens-morgenstern** [comment]
What do you mean to attach to an exiting process? I don't get what you mean exactly here.

Sending a SIGTERM is not possible because it's not possible on windows. You can do something like that on windows, by sending a similar signal to the HWND - but since not all programs have one, that doesn not work, so I don't want it in the library.

**Comment by jpvienneau** [comment]
It would be useful to create a child for an existing process by specifying a process identifier or process handle.

To complement this, a function to retrieve the set of existing processes in order to obtain the process id or handle would also be useful.

Then the ability to wait for termination or kill the process.

It this mode of operation it would be reasonable to expect the streams to be null or otherwise in accessible.

**Comment by jpvienneau** [comment]
By "terminate signal", I mean whatever termination mechanism that is available on the platform.

**Comment by klemens-morgenstern** [comment]
Oh ok, I should've gotten that type, sry. 
You can create a child from an existing pid and then terminate that. You cannot modify the already set streams of a running process - that can only be done by the child or at launching.
You cannot obtain a complete list of running processes.
You can terminate, but not as a signal. That is you can terminate the child process without notifying it or you can wait for it to exit on it's own. Posix offers a mechanic to send a signal which the child can handle to exit properly - this is not available on windows, hence not in this library.

e.g.:


```cpp
namespace bp = boost::process;
bp::pid_t p1 = get_pid_somewhere();
bp::pid_t p2 = get_other_pid();

child c1(p1);
c1.terminate();

child c2(p2);
c2.wait();

```` 

This is actually done in a [test](https://github.com/klemens-morgenstern/boost-process/blob/develop/test/group.cpp#L95)

**Comment by jpvienneau** [comment]
Thanks!
