### ISSUE TITLE
Redesign 0.6

### ISSUE THREAD

**Issue by klemens-morgenstern** [klemens-morgenstern/boost-process#2]
I'd really like to have the boost.process library, but since development was on hiatus for two years, I think a few small design changes would be nice - or rather big ones, as described below.
But, not everything I write here is completely tested. I'd really need some discussion about those and other ideas how such a library could look like, because I really would change the frontend.

Here's the [reference](http://www.highscore.de/boost/process0.5/index.html) of the current version.

@dlaugt @borisschaeling @whizmo @hotgloupi @nat-goodspeed @havoc-io @rconde01 @JeffGarland

Since we now have a variadic templates, I think the execute function can be extended and much more flexible. Please notice, that `execute` shall return an undefined type, which depends on the parameters. It might be converted to `child`, as discussed below.

# 1 Defaults
## 1.1 Unification

First of all, I like to unify the signal handling, to provide the following:

```cpp
    void on_setup(Executor&) const
    void on_error(Executor&, const std::error_code &ec) const
    void on_success(Executor&) const
```

This would require the posix-executor to always use the self-pipe in order to provide the on_success signal. Therefore I think it would be also possible to add a initializer which removes this, in the following way:

```cpp
   using namespace boost::process::initializers;
   auto p = execute("some_prog", posix::no_success_signal);
```

If then a success handler is provided, it would provide an error, i.e.:

```cpp
   using namespace boost::process::initializers;
   auto p = execute("some_prog", posix::no_success_signal, on_success([](auto){}));
   //yields an compiler error
```

### Posix Structure

The way it should work on posix is this:

![uml](http://plantuml.com/plantuml/png/TOyz2iCm38Ntd4AZFVG26RgK-XI5O5oPY8Quo4wJuyToxL08dOJUzvv-Z4qZykLgIkqXp4F4jBoLxan5jv6c9_JW0x-wqZGjY-H1UKkJbgGu1cGEVF9bYXkwOtZbzmq1X0lyuDzO6VfpKpjtjPHQwAlbqCgKy8XKMdPaipa_N9qG-37B_ujp6AFIEm00)

A possible code in posix would look like this: 

```cpp
executor::operator()(...)
{
   pipe error_pipe = create_pipe(FD_CLOEXEC); //closes the pipe on execve call
   on_setup();
   auto pid = fork();
   if (pid == -1)
      on_fork_error();
   else if (pid == 0)
   {
      ::close(selfe_pipe.source);
      on_exec_setup();
      ::execve(exe, cmd_line, env);
      on_exec_error();
      ::write(error_pipe.sink, &errno, sizeof(int));
      ::_exit(EXIT_FAILURE);
   }
   //ok, here we are back in the father-process 
   int code, cnt;
   do 
   {
     cnt = ::read(error_pipe.source, &code, sizeof(code));
      int err = errno;
      if (res == EDABF)  //pipe is closed.
          break;
       //EAGAIN not yet forked, EINTR interrupted, i.e. try again
      else if ((err != EAGAIN) && (err != EINTR)) 
      else
          throw error();
   }
   while(cnt == -1);

   if (cnt == 4) //error.
       on_error(code);
   else if (cnt > 0) //some other strang error
       on_error(...); //don't know yet
   else
       on_success();
}
```

Now, on default the father process is waiting. I think to provide a `ignore_error` would be very usefule, since this would then ignore this. 

The additional signal-handlers will be availble as part of the `boost::process::posix` namespace.

## 1.2 Throw on error

I also would make the throw_on_error the default, because it just makes the most sense, since execute constructs a process-object. I.e. not being able to construct it should result in an error.

```cpp
auto p1 = execute("not_runnable"); //throws
auto p2 = execute("not_runnable", ignore_error); //no throw, no handling;
std::error_code ec;
auto p3 = execute("not_runnable", set_on_error(ec)); //no throw, takes the error
auto p3 = execute("not_runnable", ec); //no throw, takes the error, shortcut.
```

 I would introduce `posix::no_success_signal` and `ignore_error` because the posix implementation now waits for the child-process to start. A user might consider that unneeded and could hence wish to skip that.

# 2. Simplified syntax

## 2.1. Idea

I think it would be possible to make the syntax much simpler, as in the following examples (corresponding to the current). All are equal.

```cpp
auto p1 = execute(exe("cmd"), args("x", "y")); //shortened version of the current syntax
auto p2 = execute(exe="cmd", args={"x", "y"}); //alternate syntax
auto p3 = execute(exe="cmd", args="x", args+="y"); //other syntax
auto p4 = execute("cmd", "x", "y"); //lazy syntax
auto p5 = execute(cmd("cmd x y"));
auto p6 = execute(cmd="cmd x y");
auto p7 = execute("cmd x y");
```

The cmd and args get parsed differently, that is:

```cpp
execute(cmd="cmd x y z");//yields "cmd x y z"
execute(cmd="cmd \"x y\" z");//  yields "cmd \"x y\" z"
execute(exe="cmd", args={"x y", "z"}); //yields "cmd \"x y\" z"
```

## 2.2. Other initializers

The following signal handlers shall have syntax similar to the above.
 
  - inherit_env
  - env
  - start_dir

And the platform specifics.

## 2.3 I/O

*This is the part where I am the least confident, but those are all things I consider possible.*

### 2.3.1  Close Pipe / Redirect to null

If a pipe shall be closed, it should be possible in the following way

```cpp
execute("ls", std_out=null);  //redirect to /dev/null
execute("ls", std_out=close); //close the pipe
//alternate syntax
execute("ls", std_out>null);  //redirect to /dev/null
execute("ls", close(std_out)); //close the pipe
```

### 2.3.2 Sync I/O

The sync I/O can be simplified in the following way (current [example](http://www.highscore.de/boost/process0.5/boost_process/tutorial.html#boost_process.tutorial.synchronous_i_o)). I.e. the pipe can be constructed automatically.

```cpp
file_descriptor_sink sink;
execute("my_prog", std_in=sink);//alternatively '|', because pipe.
stream<file_descriptor_sink> str;
```

```cpp
stream<file_descriptor_source> str;
execute("my_prog", std_out=str);
```

If the output shall be redirectet into a file, this can be done via a `boost::filesystem::path`:

```cpp
execute("my_prog", std_out=path("./log.txt"));
```

It may also be following to allow a lazy redirection to files:

```cpp
execute("my_prog", std_out>"./log.txt");
```

With this syntax it is of course also easy to pipe from one process to another (though the implementation is not yet clear, i might need to use a named pipe on windows)

```cpp
process::pipe = create_pipe(); 
execute("prog1", std_out>pipe);
execute("prog2", std_in<pipe);
```

### 2.3.3 Self-Sync I/O

*Removed, because that makes child struct unecessary complicated*

Another possibility, that would definitly be possible would be to allow the process to adapt to a string. I don't know it this would actually be worth the effort.

```cpp
auto p = execute("c++filt", std_in=self, std_out=self);
p << "_ZN9wikipedia7article8wikilinkC1ERKSs";
std::string dem;
p >> dem;
//dem  == "wikipedia::article::wikilink::wikilink(std::string const&)"
```

This is only convenience, it allows short-handed I/O. One could also use the stderr instead of stdout, while declaring both as self will yield an error.

### 2.3.4 Async I/O

This might be the most difficult part. I imagine that we can do it in someway like this:

```cpp
boost::asio::io_service io_service;
stringstream ss;//threadunsafe, but get's the point.
string buf; 

execute("some_prog", std_in<ss, std_out>buffer(buf), std_err>cerr, io_service);
io_service.run();
```

Thereby the whole mitigate thing can be hidden and managed automatically. Addtionally, if no io_service is passed, it could be created by the execute command and run it in another thread.

The [example](http://www.highscore.de/boost/process0.5/boost_process/tutorial.html#boost_process.tutorial.asynchronous_i_o) from the current tutorial would look like this:

```cpp
boost::asio::io_service io_service;
std::array<char, 4096> buffer;

auto p = execute("test.exe", std_out>process::buffer(buffer), io_service);

io_service.run();
```

I can determine that buffer must be read async,because it's no stream and can construct the async_pipe in place. Also I can call `async_read` from the executor, because that does only start on `io_service.run()`.
Additionally, the io_service could be skipped and constructed in the executor and launched in a new thread. Don't know if that'd be smart though.

But to be honest: I am currently not nearly familiar enough with the way `io_service` works.

The same would apply to any `std::ostream` or `std::istream`, which is not `stream<file_descriptor_sink>`, so the `cerr ` or `ss` in my example should work this way. Now of course, binding `std_err>cerr` is by far the stupidest way, because I could pipe that directly (`std_err>stderr`) - at least if we provide a syntax for that (i.e. also redirecting `std_err>stdout`).

__This whole concept needs more experimentation!__

### 2.4 Environment

In 0.5 the `inherit_env` was empty for windows, I don't know if that actually works. Now I would use the following syntax:

```cpp
execute("thingy"); //inherit env
execute("thingy", env+={"MY_VAR=Thingy"}); //inhertit and add
execute("things", env=  {"MY_VAR=Thingy"}); //do not inherit
```

So the following would be awesome, though I don't know if necessary: 

```cpp
//inherit the environment and append "MyThing" to "MY_VAR"
execute("thingy", env["MY_VAR"]+="MyThingy"};
```

# 3. Classes
## 3.1 Process

When calling execute a process-object is returned, whichs type is undefined. It holds any data needed by the initialization. It has a set of functions, which are the following

  - is_running
  - terminate
  - wait //formerly wait_for_exit
  - wait_for   //wait with a timespan to wait
  - wait_until //wait until a time timepoint
  - exit_code

## 3.2. Child

If the process shall be stored in an undefined class, it can be converted to `child`. The data is then moved onto the stack and stored in a pointer inside the child. The child class will have member-functions similar to the functions for process.
A child is movable, but not copyable.

# 4. Launch Mode

*Removed, is done via process groups #8*

In order to provide a process in an RAII way I do think that different launch modes should be available. I do not know as for now if this can be switched at runtime or has to be defined at launch time.

#### Attached

If a childprocess runs attached it will be terminated on destructor-call.

#### Detached

If a process is detached nothing will happend on destruction

### Default

By default a process is launched in an attached way. This would cause this syntax to immediately terminate the application:

```cpp
execute("prog");
```

But this behaviour could of course be specified by the following way:

```cpp
execute("prog", wait); //blocking
execute("prog", detach); //not blocking.
```

# 5 this_process

Similar to `std::this_thread` I would add a `this_process` namespace with the following synopsis.

```cpp
namespace this_process 
{
    int get_id();
    /*undefined*/ native_handle();
    environment get_environment();
}
```

**Comment by BorisSchaeling** [comment]
Thank you for reviving Boost.Process! I'm trying to remember what we did and why. :) 

## 1.1 Unification 

You are referring here to the so-called arbitrary extensions (which are as of today on_CreateProcess_setup, on_CreateProcess_error, on_CreateProcess_success and on_fork_setup, on_fork_error, on_fork_success, on_exec_setup and on_exec_error)? Or are you also referring to the handlers in initializers (which are as of today on_CreateProcess_setup, on_CreateProcess_error, on_CreateProcess_success and on_fork_setup, on_fork_error, on_fork_success, on_exec_setup and on_exec_error)? 

Yes, the handlers have the same names as the arbitrary extensions (actually the arbitrary extensions were named after the handlers). If the arbitrary extensions are unified, I would expect that the handlers are unified, too? 

Unifying names means that you give up distinguishing between fork and exec on POSIX platforms? When would on_setup be called on POSIX platforms - before fork or before exec? How would an initializer like [notify_io_service](https://github.com/BorisSchaeling/boost-process/blob/master/boost/process/posix/initializers/notify_io_service.hpp) be implemented which may need to do different things before fork and before exec? 

## 1.2 Throw on error

Throwing an exception by default sounds like a good idea to me. I wouldn't need any other option apart from passing std::error_code (nothing against posix::no_success_signal and ignore_error; but there are lots of functions in Boost which either throw or return an error - everyone seems to be fine with these two options :). 

# 2. Simplified syntax

I like the idea of named parameters (but I'm not sure whether we can cover all use cases sufficiently; still a nice idea which I would like to see being explored). 

If `execute(cmd="cmd x y");` is supported, you may need to specify how the string is parsed (think of quotes and other special characters like in `execute(cmd="cmd \"x y\" z");` - are these two or three command line arguments?). 

(More later.)

**Comment by klemens-morgenstern** [comment]
# 1.1 Unification.

No, I would keep the posix ones in, as posix extensions. It's just a unified interface, which basically means, that the current posix implemenation get's two more signal handlers.
The executor waits for the child-process to start via a pipe, as did the `throw_on_error`. On_success and on_error may be called there. Additionally we need the on_fork_success exactly for the io_service.

So you have the three handlers

  - on_success
  - on_error
  - on_setup

which happen to be the same windows uses, but they can be used as arbitrary extensions in a portable way. Posix has two more (`on_fork_succes` and `on_fork_error`), which would be available on posix platforms and which would be used to notify the io_service. This is because the io-service implementation is platform-specific. But at least set_on_error can be a platform-independent handler. 

## 1.2 Throw on error

Well I would introduce `posix::no_success_signal` or `ignore_error` because the posix implementation now waits for the child-process to start. A user might consider that unneeded and could hence wish to skip that. 

# 2. Simplified Syntax

Good point! I think the rules could be defined as follows

```cpp
execute(cmd="cmd x y z");//  yields "cmd x y z"
execute(cmd="cmd \"x y\" z");//  yields "cmd \"x y\" z"
execute(exe="cmd", args={"x y", "z"}); //yields "cmd \"x y\" z"
```

**Comment by BorisSchaeling** [comment]
## 1.1 Unification

If I understand correctly the POSIX executor would call on_success instead of on_fork_success, on_error in addition to on_fork_error and on_exec_error and on_setup in addition to on_fork_setup? 

# 2. Simplified Syntax

I remember now that we have a [set_cmd_line initializer](http://www.highscore.de/boost/process0.5/boost/process/initializers/set_cmd_line.html) which accepts a string like "cmd \"x y\" z". I think the initializer simply forwards the string to whatever API functions are called to create the process (which means the string is parsed by platform-specific API functions).

**Comment by klemens-morgenstern** [comment]
No, because the on fork success is called on another process already, which is quite bad in my opinion. So the way I'd it is this (pseudo-code anyway) :

```cpp
executor::operator()(...)
{
   pipe error_pipe = create_pipe(FD_CLOEXEC); //closes the pipe on execve call
   on_setup();
   auto pid = fork();
   if (pid == -1)
      on_fork_error();
   else if (pid == 0)
   {
      ::close(selfe_pipe.source);
      on_exec_setup();
      ::execve(exe, cmd_line, env);
      on_exec_error();
      ::write(error_pipe.sink, &errno, sizeof(int));
      ::_exit(EXIT_FAILURE);
   }
   //ok, here we are back in the father-process 
   int code, cnt;
   do 
   {
     cnt = ::read(error_pipe.source, &code, sizeof(code));
      int err = errno;
      if (res == EDABF)  //pipe is closed.
          break;
       //EAGAIN not yet forked, EINTR interrupted, i.e. try again
      else if ((err != EAGAIN) && (err != EINTR)) 
      else
          throw error();
   }
   while(cnt == -1);
   
   if (cnt == 4) //error.
       on_error(code);
   else if (cnt > 0) //some other strang error
       on_error(...); //don't know yet
   else
       on_success();
}
```

I hope that makes somewhat sense.

**Comment by BorisSchaeling** [comment]
Thanks, this helped! If I understand now correctly, this is what happens: 

- on_fork_setup is renamed to on_setup 
- on_fork_success is renamed to on_success 
- on_error is added and called in addition to on_exec_error (and probably on_fork_error?)

**Comment by klemens-morgenstern** [comment]
Well `on_success` is called after `execve` succeeded, not after the fork. 

Of course the `on_error` must be called after `on_fork_error`, which is not right in the code I posted.

**Comment by BorisSchaeling** [comment]
I was comparing with the [current implementation](https://github.com/BorisSchaeling/boost-process/blob/master/boost/process/posix/executor.hpp) where on_success would replace on_fork_success (there is no on_exec_success).

**Comment by klemens-morgenstern** [comment]
Yes it basically replaced it, though it waits for the `execve` to start. If the `on_fork_success` is needed as it was implemented before (which might me necessary for the io_service) it would be before the do-while look. because the io_service must be informed after a fork.

**Comment by BorisSchaeling** [comment]
### 2.3.1 Close Pipe

I find `std_out=nullptr` and `std_out=boost::none` strange. I'm not sure whether stdout is closed or redirected to /dev/null. I guess it's closed. But then I definitely prefer `std_cout=close`.

### 2.3.2 Sync I/O

Looks very nice (both the named parameter syntax and redirecting with < or >)! 

### 2.3.3 Self-Sync I/O

I'm not sure what's going on here. 42 is sent to stdin of the child process and read from stdout again? 

### 2.3.4 Async I/O 

I think I need to see some more code. Not sure whether it's a bit too early - if it isn't, can you try to rewrite [this example](http://www.highscore.de/boost/process0.5/boost_process/tutorial.html#boost_process.tutorial.asynchronous_i_o) which is trying to read asynchronously from stdout of the child process?

**Comment by klemens-morgenstern** [comment]
## 2.3.1 Close Pipe

Darn, my bad! Yeah of course closing the pipe is different than redirecting it to null. I just looked at it and thought: *well, then he doesn't seem to use it.*  Those evil details get me all the time.

Wouldn't it then make more sense to actually provide both? I.e. `close` and `null` ?

# 2.3.3 Self-Sync I/O

Yep. An example that would come to mind is c++filt, i.e.

```cpp
auto p = execute("c++filt");
p << "_ZN9wikipedia7article8wikilinkC1ERKSs" ;
std::string dem;
p >> dem; 
//p == "wikipedia::article::wikilink::wikilink(std::string const&)"
```

# 2.3.4 Async I/O

Yeah, that gets messy, Though I can assure you: it's too early!

So the example from the tutorial should look like this.

```cpp
boost::asio::io_service io_service;
std::array<char, 4096> buffer;

auto p = execute(exe="test.exe", std_out>buffer, io_service);

io_service.run();
```

I can determine that buffer must be read async,because it's no stream and can construct the async_pipe in place. Also I can call `async_read` from the executor, because that does only start on `io_service.run()`.
Additionally, the io_service could be skipped and constructed in the executor and launched in a new thread. Don't know if that'd be smart though.

Now the same would apply to a `std::ostream` or `std::istream`, which is not `stream<file_descriptor_sink>`, so the `cerr ` or `ss` in my example work this way. Now of course, binding `std_err>cerr` is by far the stupidest way, because I could pipe that directly (`std_err>stderr').

But to be honest: I am currently not nearly familiar enough with the way `io_service` works.

**Comment by BorisSchaeling** [comment]
### 2.3.1 Close Pipe

I agree - `execute("ls", std_out=close)` and `execute("ls", std_out=null)` look self-explanatory to me. :) I guess the latter one could also be written as `execute("ls", std_out>null)`. 

### 2.3.3 Self-Sync I/O

I think the example covers various details. I understand that the return type of execute() overloads the stream operators? Writing means sending data to the child process' stdin and reading means receiving data from the child process' stdout? This would be a convenience function so that one doesn't need to create a pipe and manually wire up the child process' stdin and stdout streams? 

### 2.3.4 Async I/O

I leave this for later (I'm still missing some details here). 

# 4. Launch Mode

Regarding RAII: Yes, this could be one of the more difficult problems. But I like your idea with launch modes (reminds me of std::thread :).

**Comment by klemens-morgenstern** [comment]
### 2.3.3 Sefl-I/O

Yeah, that's just convenience as you described. You could also use `std_err`as the `ostream` by writing `std_err=self`, which means, that using both `std_err` and `std_out` at the same time must yield an error.

# 4. Launch Mode

Yes, that's were I got the idea. If the detaching works after launch on both systems, we could even use the same interface ;).

**Comment by klemens-morgenstern** [comment]
Just fyi: I'd like to use [boost.hana](https://github.com/boostorg/hana) instead of boost.fusion.
It's already approved for boost, but it doesn't compile with gcc yet (5.3) - though with clang 3.7. I think gcc 6 will be supporting this.
Is support for older compilers crucial for some reason?

**Comment by BorisSchaeling** [comment]
Feel free to use Boost.Hana! We can provide multiple implementations later if we really want or need to. :)

**Comment by klemens-morgenstern** [comment]
Question: how does the whole `inherit_env`work? From what I see in the code, it seems like windows would inherit always and it's optional on linux. Now that would be bad, since it not consistent accross platforms. 
But the MSDN tells me, that windows could actually overwrite the environment ( is there any experience with that?  )

Here's what I'd do:

```cpp
execute("thingy"); //inherit env
execute("thingy", env+={"MY_VAR=Thingy"}); //inhertit and add
execute("things", env=  {"MY_VAR=Thingy"}); //do not inherit
```

So the following would be awesome, though I don't know if necessary: 

```cpp
//inherit the environment and append "MyThing" to "MY_VAR"
execute("thingy", env+={env_var["MY_VAR"]+="MyThingy"};
```

Thoughts?

**Comment by klemens-morgenstern** [comment]
### Status update

Reworking the whole MPL stuff with Hana took a bit more time than expected, though I have to say: hana is awesome.

I think the basic structure is now alright, though it'll take a lot of time, to now implement the actual initializers.

Currently you can launch a process from a string and handle the error (throw, assign, ignore). Throw on default.

I decided to remove the self-pipe feature, since it overcomplicates the child for a small convenience.

If someone is interested you might look at the following files (and yes, it's till messy)

  - test/run_exe.cpp
  - include/boost/process/execute.hpp
  - include/boost/process/windows/executor.hpp
  - include/boost/process/cmd.hpp
  - include/boost/process/error.hpp

**Comment by klemens-morgenstern** [comment]
### Status update

Sync I/O works as far as the _bind_*_ and the _close_*_ tests are concerned. The async-io stuff is not yet in, but hopefully follow soon.

**Comment by klemens-morgenstern** [comment]
# Status update

I have basically every feature I'd like to have in boost.process somewhat working on windows.

The next steps will be:
 
  1. Major Cleanup (yeah, don't look at the code as of yet...it's a mess..)
  2. Documentation
  3. Starting on the Posix-Version
  4. Annoying everybody on the boost mailing lists and not only @borisschaeling
  5. Implement error handling

I might also as a part of Step 1 remove the usage on hana and implement the meta-stuff myself and thereby downgrade the whole thing to C++11 (Though I promise nothing!).. That is because Hana is not widely supported and it's style bloats the binaries incredibely.

**Comment by klemens-morgenstern** [comment]
Ok, it's in alpha now, so the design is finished. Please see the doc if you're interested: http://klemens-morgenstern.github.io/process/
