### ISSUE TITLE
Compile errors when using boost::process::null

### ISSUE THREAD

**Issue by hotgloupi** [klemens-morgenstern/boost-process#20]
Hi, I'm trying to use the develop branch against boost 1.55 using g++4.8 in c++11 mode.

I'm trying to compile a simple hello world:

```
#include <boost/process.hpp>

namespace bp = boost::process;

int main()
{
    std::string cmd = "echo 'Hello, world!'";

    bp::child child(
        cmd,
        bp::shell,
        bp::std_in.close(),
        bp::std_err > bp::null,
        bp::std_out > bp::null
    );

    child.wait();
    return child.exit_code();
}
```
But I get those errors:

```
$ g++ -std=c++11 test.cpp -I src -I /boost-1.55/include
In file included from src/boost/process/io.hpp:22:0,
                 from src/boost/process.hpp:30,
                 from test.cpp:1:
src/boost/process/detail/posix/null_out.hpp: In instantiation of ‘boost::process::detail::posix::null_out<p1, p2> boost::process::detail::std_out_<p1, p2>::operator>(const boost::process::detail::null_t&) const [with int p1 = 2; int p2 = -1]’:
test.cpp:13:27:   required from here
src/boost/process/detail/posix/null_out.hpp:21:8: error: converting to ‘boost::process::detail::posix::file_descriptor’ from initializer list would use explicit constructor ‘boost::process::detail::posix::file_descriptor::file_descriptor(const char*, boost::process::detail::posix::file_descriptor::mode_t)’
 struct null_out : handler_base_ext
        ^
In file included from src/boost/process.hpp:30:0,
                 from test.cpp:1:
src/boost/process/io.hpp:136:87: note: synthesized method ‘constexpr boost::process::detail::posix::null_out<2, -1>::null_out()’ first required here
     api::null_out<p1,p2> operator>(const null_t &) const {return api::null_out<p1,p2>();}
                                                                                       ^
In file included from src/boost/process/io.hpp:22:0,
                 from src/boost/process.hpp:30,
                 from test.cpp:1:
src/boost/process/detail/posix/null_out.hpp: In instantiation of ‘boost::process::detail::posix::null_out<p1, p2> boost::process::detail::std_out_<p1, p2>::operator>(const boost::process::detail::null_t&) const [with int p1 = 1; int p2 = -1]’:
test.cpp:14:27:   required from here
src/boost/process/detail/posix/null_out.hpp:21:8: error: converting to ‘boost::process::detail::posix::file_descriptor’ from initializer list would use explicit constructor ‘boost::process::detail::posix::file_descriptor::file_descriptor(const char*, boost::process::detail::posix::file_descriptor::mode_t)’
 struct null_out : handler_base_ext
        ^
In file included from src/boost/process.hpp:30:0,
                 from test.cpp:1:
src/boost/process/io.hpp:136:87: note: synthesized method ‘constexpr boost::process::detail::posix::null_out<1, -1>::null_out()’ first required here
     api::null_out<p1,p2> operator>(const null_t &) const {return api::null_out<p1,p2>();}
```

**Comment by klemens-morgenstern** [comment]
I think this is a compiler bug fixed in gcc 4.9.1, I found a description of that [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58930)

How restricted are you in using gcc 4.8? Because I could add a workaround, but I really don't like to; It's standard-conforming (I think) and that's my benchmark in development. Especially since I don't think I can workaround #21.

**Comment by hotgloupi** [comment]
Well, It's really hard for me to upgrade our compiler, as I'm already using a devtoolset for centos 6 ...
Also, about #21, allowing the copy contruction is not safe ? (this might explain some fonctional bugs I have ...)

**Comment by klemens-morgenstern** [comment]
Uhm, I didn't test that (obviously) but I guess it should be safe. I'v tested this code on gcc 5.4, 6.0 and msvc 2014.

I'd like to help you but if I got time to work on boost.process currently, I'll have to invest it to work on `wchar_t` support, so windows users can use more than ascii for the prorams (e.g. `dämlich.exe`).

If you create a PR with the fitting compiler switch, I'll gladly accept it; I really don't have the time (because I'd need to test it on both platforms and apply this workaround to all properties). I think the code for `null_out` would need to be something like that:

```cpp
template<int p1, int p2>
struct null_out : handler_base_ext
{
    null_out() : file("/dev/null") {} 

    template <typename Executor>
    void on_exec_setup(Executor &e) const;
};
```

Not problem, but with #21 I'd really need to have a switch.

**Comment by klemens-morgenstern** [comment]
Btw.: what's the functional bug you have?

**Comment by hotgloupi** [comment]
Hi, thanks for your quick replies, I know you're busy trying to handle the boost review process :)

I'm willing create PRs, which sounds easier than rolling my own buggy implementation of processes again. I'll get back to you soon, about the `null_out` class.

About the `cmd_init_exe` copy ctor, do you see any harm in enabling it ? if the move ctor is possible, I believe that the compiler will use it, no ?

Finally about the functional bug, I can open another issue about it, I was afraid my little change in the ctor was the cause of it. Anyway, I'm spawnin multiple processes with an io service. when some `child.running()` returns false, I retrieve and print the output (stored in a `std::future<std::string>`). The bug is that the sometimes the processes' outputs are empty for no reason (I run dummy commands like `date` or `echo lol`). Will try to create a simple reproducer and create a new issue for it. Just wanted to make sure that enabling the copy ctor was not causing some spurious undefined behavior first :)

**Comment by klemens-morgenstern** [comment]
I don't see any problem copying it. THe reason it tries to copy is, that boost.fusion tries to copy, while it could move. I don't know if that's a compiler switch of is boost 1.55 is too old. Btw: you'd need boost 1.62 on windows, if you need to try that.

To the bug: did you pass a `boost::asio::io_service`also? It should fail to compile, if you don't but you never know. If you do that you need to run it, too. But yeah a minimal example would be awesome.
Using `shell` has a few issues, i.e. if your command fails the shell will still launch properly, so you don't get an error there. I just realized that lately, so I'll need to add it to the doc.

**Comment by hotgloupi** [comment]
I've created the #22 issue about the async problem (btw, on my platform, it's not possible to forget the io_service argument, but the error is very cryptic).

About the copy being safe, I will create a pull request that just enable it. I think it might be that Boost.Fusion use the correctly the move ctor on master, but not 1.55. I hope it will keep using the move ctor when possible ...

Cheers,

**Comment by klemens-morgenstern** [comment]
I'd be really glad to know why that is. Because that might become an even bigger issue with the `wchar_t` feature I'm currently working on. If it's a boost.fusion issue, I won't touch it, because `boost.process` will not ship before 1.63, and that's if I'm lucky.

**Comment by klemens-morgenstern** [comment]
If you're still having this problem, please feel free to create a PR. I'm really not fond of open PRs where it doesn't seem a solution is coming around soon.

Btw: the whole story about copying got more critical after I added `wchar_t`, since a mishandling in boost.fusion would now lead to several copies and not just one.
