### ISSUE TITLE
Impossible to create a process with an empty environment on windows

### ISSUE THREAD

**Issue by barcharcraz** [klemens-morgenstern/boost-process#204]
https://github.com/klemens-morgenstern/boost-process/blob/6ccce9104ae91f6d07ac64c6d4e5fc0b57a649fe/include/boost/process/detail/windows/env_init.hpp#L40

as seen in the above line boost::process checks if the process is empty and if so gives up immediately on windows. This contradicts the docs, and is also extremely annoying.

It's also not super appropriate to set a winapi error code for something that doesn't actually come from the windows api

**Comment by klemens-morgenstern** [comment]
The alternative is a Segfault coming from the windows api.
