### ISSUE TITLE
wait_for() leaves the process hanging on MacOSX

### ISSUE THREAD

**Issue by emmenlau** [klemens-morgenstern/boost-process#205]
Since boost 1.70.0 I'm plagued by a new issue on MacOSX. When I use `boost::process::child::wait_for()` to wait for the termination of a child, it seems like the parent process hangs after the end of `main()` indefinitely with 100% CPU. This is after control is returned to the shell, it it may be a forked copy of the main process.

The same code works well on Linux (Ubuntu 18.04 x86_64 and Windows with Visual Studio 2017). The code also works on MacOSX when I replace `wait_for()` with `wait()`.

Here is a rough outline of what I'm doing:
```
    boost::process::ipstream mProcessStdOutStream = boost::process::ipstream;
    std::thread mStdOutProcessor = std::thread(&processStdOut, this);

    boost::process::child mProcess =
        boost::process::child("/bin/date", "+%s",
                                           boost::process::std_in.close(),
                                           (boost::process::std_out & boost::process::std_err) > mProcessStdOutStream);
    bool vProcessEnded = mProcess->wait_for(std::chrono::seconds(1));
```
I get correctly `vProcessEnded` that the child process ended, and when I check the childs return code I can see that it was successful.

But the main executable (or some process with the same name) remains hanging in the background with 100% CPU even after `main()` returned control to the shell!

**Comment by klemens-morgenstern** [comment]
This is a known issue and I am very sorry for screwing that up. I changed the functions in 1.71, so it should be fixed.

**Comment by emmenlau** [comment]
Ok great, then its all fine! I'm happy to know it'll work soon again! Happy coding and all the best.
