### ISSUE TITLE
Why does async_system return a boost::asio::result_type

### ISSUE THREAD

**Issue by jonesmz** [klemens-morgenstern/boost-process#206]
There's no explanation in the documentation that gives any hint as to why this type is returned.

https://www.boost.org/doc/libs/1_65_0/doc/html/boost/process/async_system.html

**Comment by klemens-morgenstern** [comment]
It says it right there: *[...] but is similar to the asynchronous functions in boost.asio*

*It uses asio::async_result to determine the return value (from the second parameter, exit_handler).*

Take one look at `boost::asio` and it'll make sense.

**Comment by jonesmz** [comment]
Except that doesn't actually answer my question, or explain what the returned type does.

Boost::asio has very obtuse documentation which does a poor job of explaining what it does and how, and boost::process is significantly less clear.

The second parameter `exit_handler` is required to return void, according to the API documentation provided by boost::process, so I am struggling to understand how the returned async_result object will do any good.

I also dug pretty deep into the boost::process code, and can't figure it out.

**Comment by jonesmz** [comment]
I'd also like to know why async_system doesn't return the `child` object, so that the calling function can interact with it.

**Comment by klemens-morgenstern** [comment]
If you had asked a question, I would've answered it.

`async_system` is an asynchronous version of `system`, i.e. it executes the process and invokes the completion handler following the pattern of `boost::asio`. So you can also use `use_future` or `yield_context`.

That whole thing won't make much sense though unless you did something with `asio`. I don't know what you're trying to do, but I suspect just using the `child` constructor is what you actually want.

**Comment by jonesmz** [comment]
> If you had asked a question, I would've answered it.

Er.. I did? I asked why boost::process::async_system returns a boost::asio::result_type. 

> async_system is an asynchronous version of system, i.e. it executes the process and invokes the completion handler following the pattern of boost::asio. So you can also use use_future or yield_context.

I've seen several references to `use_future` in the boost::process documentation, but so far have failed to find an explanation of how, or why, i would do so. It would be helpful to users of the library if the documentation were enhanced to explain this.

> That whole thing won't make much sense though unless you did something with asio. I don't know what you're trying to do, but I suspect just using the child constructor is what you actually want.

I have a 5 thousand line application that's been using boost::process::async_system, and boost::asio, for a variety of tasks. These tasks must be run asynchronously, as I have a variety of other actions taking place in this application.

Recently I needed to add functionality that would terminate a child process that was started by my existing code that calls boost::process::async_system() if a timeout triggers before the child process finished executing.

What's missing in the documentation, or inline comments, is the full list of arguments that can be supplied to boost::process::child, and what they do.

I'm struggling to contend with the sparse wording in each section of the documentation, and the several sections that have sentences that aren't finished. 

For example, the mechanism that boost::process::async_system uses to run the child process in an async context is this object:

`detail::async_system_handler<ExitHandler> async_h{ios, std::forward<ExitHandler>(exit_handler)};`

But I can't find any information on what this is in the documentation, even though I can read the code for it to try to make a guess as to what is going on.

Or, another example: the functionality of "boost::process::child::detach" isn't really documented well. It says:

"Detach the child, i.e. let it run after this handle dies."

But what this doesn't explain to the user is that calling detach() only sets a bool, and doesn't stop the user from continuing to use the child object normally after its called.

Ultimately I've solved my problem by copying the entire `boost::async_system` function, e.g. `boost::async_system2`, and have my version return the child object so that I can call `child::terminate` if needed.

**Comment by klemens-morgenstern** [comment]
I think what you actually want is [`on_exit`](https://www.boost.org/doc/libs/master/doc/html/boost/process/on_exit.html).

`async_system` is meant to be used for short run proceses that do not need to be terminated. So that's a design choice. 
What `async_result` is giving you is a generalization of a promise, giving you either the exit_code or an error.

**Comment by jonesmz** [comment]
No, I definitely do not want `on_exit`. I need to be able to terminate child processes that are executing for longer than allowed.

Yes, I understand what `async_system()` is meant for, but there are no facilities in `boost::process` that do what I need. `async_system()` is the closest to my goal, so I had to copy `async_system()` and modify it.

Your explanation of `async_result` does not explain how to use it, or why it's returned from `async_system()`.

There's a lot of things that asked about in my several comments on this post.

I'd like to have a full discussion about them, both so that I can personally be informed on the topics, and also so that we can improve the documentation of boost::process for other's benefits.

Can you please go into more detail, and address the various topics that I've brought up?

**Comment by klemens-morgenstern** [comment]
- [`async_result`](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/async_result.html).
 - [`use_future`](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/reference/use_future_t.html)

To illustrate that for `async_system`, which imitates the behaviour of any 

```cpp
//use a callback
boost::process::async_system(ioc, [](auto ec, int exit_code){...});

//use a future
future<int> exit_code = boost::process::async_system(ioc, boost::asio::use_future);

//or inside a (stackful) coroutine
int exit_code = boost::process::async_system(ioc, yield_);
```

I would need more details on your application, do you achieve asynchronous behaviour by callbacks or any other means?

**Comment by jonesmz** [comment]
The behavior of my application is not really why I opened this issue.

I'm trying to point out parts of the `boost::process` documentation that are insufficient for even moderately experienced C++ developers (I have been using C++ for async programming for about 10 years now) to understand what your library is doing.

Can we discuss the documentation, and how to improve it?

**Comment by jonesmz** [comment]
That being said, I use callbacks.

**Comment by klemens-morgenstern** [comment]
I am open to improvement of the documentation, but it quite unlikely that I will get around to writing a lot any time soon.

**Comment by klemens-morgenstern** [comment]
The issue you picked is directly inherited from `boost.asio`, and `boost.process` uses the `async_result` in the same way every single `async_*` function in `asio` does. It determines what kind of return value is used given the type of completion-handler. `async_result` is an extension point, `boost.fiber` for example defines it's own.

If you pass in a callback, the return type is `void`. If you pass in `use_future` it is a future, if you pass in a `yield_context` it's the value; and I think there's experimental support for `co_await`, too now.  The idea is that you can avoid call-back hell with that. 

But again: this is a feature of `boost.asio`, not of `boost.process`.

**Comment by jonesmz** [comment]
Well, frankly, `boost::asio` does a bad job explaining any of that, itself.

As for `boost::asio` vs `boost::process`, I think it's important to realize that it's really important, for a library usability perspective, to ensure that the documentation provided for `boost::process` not assume that the end-user understand anything about `boost::asio` beyond the very basics.

Thank you for the explanation, that helps a lot.

You should basically copy-paste the answer you just gave me straight into the documentation for `boost::process::async_system`
