### ISSUE TITLE
file descriptor leak on linux

### ISSUE THREAD

**Issue by killerbot242** [klemens-morgenstern/boost-process#207]
I had created a fix for this, but where I just don't seem to be able to create a pull request out of it, git is so complex :-(

My fix is more ore less obsolete, since I noticed that in the mean time the development branch contains a solution for it. Nevertheless I will describe my fix here, since I had one extra line as part of my fix, about an early return.
My fix is all in the _read_error function, at special points I am calling ::close(source), which is as said obsolete as fix since there is now a pipe_guard construct in place.
`
    void _read_error(int source)
    {
        int data[2];

        _ec.clear();
        int count = 0;
        while ((count = ::read(source, &data[0], sizeof(int) *2 ) ) == -1)
        {
            //actually, this should block until it's read.
            auto err = errno;
            if ((err != EAGAIN ) && (err != EINTR))
                set_error(std::error_code(err, std::system_category()), "Error read pipe");
        }
        if (count == 0)
        {
            ::close(source);  //<=========== fix
            return  ;
        }

        std::error_code ec(data[0], std::system_category());
        std::string msg(data[1], ' ');

        while (::read(source, &msg.front(), msg.size() ) == -1)
        {
            //actually, this should block until it's read.
            auto err = errno;
            if ((err == EBADF) || (err == EPERM))//that should occur on success, therefore return.
            {
                ::close(source);  //<=========== fix
                return;
            }
                //EAGAIN not yet forked, EINTR interrupted, i.e. try again
            else if ((err != EAGAIN ) && (err != EINTR))
            {
                ::close(source);  //<=========== fix
                set_error(std::error_code(err, std::system_category()), "Error read pipe");
                return;  ///<============ return, no more need to loop
            }
        }
        ::close(source);  ///<=== this line existed in 1.70
        set_error(ec, std::move(msg));
    }
`

Notice the line above :
                return;  ///<============ return, no more need to loop

===> there is no need to continue the loop I think, and we should return

What do you think ?

**Comment by killerbot242** [comment]
a bit higher in the code another such construct exists where one does not return, so maybe there it should also be needed, but I am not well suited to judge, so before I create a pull request, awaiting your view on the topic.

So we have 2 areas which go like : 
            if ((err != EAGAIN ) && (err != EINTR))
                set_error(std::error_code(err, std::system_category()), "Error read pipe");

should they have a return statement added or not ?

**Comment by klemens-morgenstern** [comment]
Can I close this with the current pip_guard?
