### ISSUE TITLE
Extra warnings on MSVC 2019

### ISSUE THREAD

**Issue by fsmoke** [klemens-morgenstern/boost-process#214]
Hello, I have extra warnings at level=3, see log below:

`D:\libraries\boost_1_72_0\boost\process\detail\windows\handle_workaround.hpp(239,158): warning C4191: 'reinterpret_cast': unsafe conversion from 'boost::winapi::FARPROC_' to 'boost::process::detail::windows::workaround::nt_system_query_information_p'
1>        Calling this function through the result pointer may cause your program to fail (compiling source file ..\..\src\main_window.cpp)
1>D:\libraries\boost_1_72_0\boost\process\detail\windows\handle_workaround.hpp(239,158): warning C4191: 'reinterpret_cast': unsafe conversion from 'boost::winapi::FARPROC_' to 'boost::process::detail::windows::workaround::nt_system_query_information_p'
1>        Calling this function through the result pointer may cause your program to fail (compiling source file ..\..\src\server_view.cpp)
1>D:\libraries\boost_1_72_0\boost\process\detail\windows\handle_workaround.hpp(239,158): warning C4191: 'reinterpret_cast': unsafe conversion from 'boost::winapi::FARPROC_' to 'boost::process::detail::windows::workaround::nt_system_query_information_p'
1>        Calling this function through the result pointer may cause your program to fail (compiling source file ..\..\src\server_view_backups.cpp)`

PS
Visual Studio 2019 version 16.5.1

**Comment by klemens-morgenstern** [comment]
Yes, that's because of my attempt trying to hide the winapi. `#define BOOST_USE_WINDOWS_H` should solve this.l
