### ISSUE TITLE
Enable ability to set the job object to kill children processes if the parent dies

### ISSUE THREAD

**Issue by kannon92** [klemens-morgenstern/boost-process#216]
https://stackoverflow.com/questions/56972219/automatically-destroy-child-process-created-via-boostprocess

Right now, on windows and linux, if I kill the master process the child process gets orphaned.  I thought that enabling a job object would save that but it looks to be only the case if the application exists gracefully.  The destructor of process group will cleanup processes.  

On windows, we set the parameter JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE on the group handle.  This will satisfy the problem of children being orphaned if the master is killed.  

````inline void enable_break_away(::boost::winapi::HANDLE_ h)
{
    workaround::JOBOBJECT_EXTENDED_LIMIT_INFORMATION_ info;
    if (!workaround::query_information_job_object(
                    h,
                    workaround::JobObjectExtendedLimitInformation_,
                    static_cast<void*>(&info),
                    sizeof(info),
                    nullptr))
        throw_last_error("QueryInformationJobObject() failed");
    if ((info.BasicLimitInformation.LimitFlags & workaround::JOB_OBJECT_LIMIT_BREAKAWAY_OK_) != 0)
        return;
    info.BasicLimitInformation.LimitFlags |= workaround::JOB_OBJECT_LIMIT_BREAKAWAY_OK_;
    **_// I wrote this into boost to set a flag.  Surprised it worked._**  
    info.BasicLimitInformation.LimitFlags |= JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;
    if (!workaround::set_information_job_object(
                h,
                workaround::JobObjectExtendedLimitInformation_,
                static_cast<void*>(&info),
                sizeof(info)))
        throw_last_error("SetInformationJobObject() failed");
}

**Comment by klemens-morgenstern** [comment]
Would love to add this, do you have an idea how to achieve the same on posix?

**Comment by kannon92** [comment]
Hello, I just figured out how to enable this on linux.  It is a bit cleaner than windows once I figured out the option.  
~~~
	boost::process::group grp;
	auto onSetup = [](auto& exec)
	{
		int r = prctl(PR_SET_PDEATHSIG, SIGTERM);
	};
	bp::child childProc(cmd, 
		ex::on_exec_setup = onSetup, 
		bp::std_in.close(),
		bp::std_out > dataOut, //so it can be written without anything
		bp::std_err > dataError,
		ios,
		ec);
~~~

I found this SO post helpful in figuring out how to get it.  And thanks to your documentation for showing that there was a possibility to call code inside of the child before calling exec.

**Comment by emmenlau** [comment]
I just stumbled over this same issue and found it to be quite a severe problem. I think many people may not be aware that when the terminate handler is called, normal cleanup routines may not be invoked and therefore child processes may continue running as zombies. At least I was not connecting the dots until now, as obvious as it may seem in retrospect.

In any case, it would be a very very valuable extension for boost:process to have a way to ensure that children are reaped when the parent ends.

The solution for Windows seems to match the one given on SO here: https://stackoverflow.com/a/4657392/7200132, and is seems very promising.

The related discussion on SO for Linux/Posix has interesting pointers here: https://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits

@klemens-morgenstern anything I can do to help this move forward? Its very relevant to us. Thanks a lot for your great work and consideration.

**Comment by klemens-morgenstern** [comment]
Moving to boostorg/process.
