### ISSUE TITLE
Linux: on_exit error when using synchronous calls

### ISSUE THREAD

**Issue by marekvinkler** [klemens-morgenstern/boost-process#217]
When using the asynchronous `on_exit` callback together with synchronous calls such as `child.running()` or `child.terminate()` the `on_exit` will receive and error code instead of the proper exit code on Linux.

The problem appears to be, that not all code paths properly handle update of the exit code after a call to `waitpid`. For example if the `waitpid` is collected by `boost::process::detail::posix::terminate` the exit code is not updated at all and is discarded.

If the `waitpid` is handled by `boost::process::detail::posix::is_running` the `child._exit_status` is updated to a correct value but a subsequent call to `waitpid` in `boost::process::detail::posix::sigchld_service` will collect `waitpid` error and will call the `on_exit` handler with `-1` and `ECHILD`. What is worse in this scenario, the `-1` value then overwrites the synchronously read `child._exit_status` in the `boost::process::detail::posix::io_context_ref::on_success` making even a workaround impossible.

I suggest that all occurrences of `waitpid` should update the `child._exit_status` and the ones that collect error should first check whether the `waitpid` wasn't already done.

**Comment by klemens-morgenstern** [comment]
Hi, thanks for reporting that, I will look into that. It might take a while though, do you have a test case I could add?

**Comment by marekvinkler** [comment]
Hi,
the test case is a bit problematic, since this is fundamentally a race on the `waitpid`. But I think the `mixed_async` test case that you already have (but commented out) should do the trick. Either `c.wait()` will succeed in collecting the `waitpid` (more likely) and `on_exit` will be called with error code or the `on_exit` will succeed and `waitpid` will throw.

**Comment by klemens-morgenstern** [comment]
on_exit was a mistake, see v2 on boostorg/process, which does it properly with an `async_wait` on the process class.
