### ISSUE TITLE
Zombie process In Boost:: process::wait_until(wait_for_exit.hpp) 

### ISSUE THREAD

**Issue by amritanshujohri** [klemens-morgenstern/boost-process#221]
@klemens-morgenstern I presume to file a ticket against this repo is the best way to get your attention. I have already filed one here See https://github.com/boostorg/process/issues/178

I have observed Z processes for MacOSX when we use Boost::Process::wait_until(), I see it on 1.73, but the offending code exists in 1.74 as well. 

```
// child_cleaner is a class responsible for cleaning up the fork() used to simulate sigtimedwait()

 struct child_cleaner_t
    {
        pid_t pid;
        ~child_cleaner_t()
        {
            int res;
            ::kill(pid, SIGKILL); 
            ::waitpid(pid, &res, WNOHANG); <-- wait with WNOHANG can result in process leak as the kill is async 
// for short-run cmd that terminate quickly there is a clear repro. If it were up to me, I would remove WNOHANG here as the child process will eventually terminate. or at least queue a wait in a cleanup thread.
        }
    };

```

Steps to repro:
```

const auto& cmdLine = boost::str(boost::format("/usr/bin/time"));
	for(int i = 0; i <100; i++)
	{
		boost::process::child x(cmdLine, boost::process::std_out > boost::process::null, boost::process::std_err > boost::process::null);
		x.wait_for(std::chrono::seconds{10});
	}
```
I hope this is the best way to approach the community if you think I should talk to some DL or group elsewhere then do let me know.

**Comment by klemens-morgenstern** [comment]
Sorry for not responding earlier, I have seen the issue on the other repo.

**Comment by amritanshujohri** [comment]
Should I close this? I am willing to fix this as well as long as I am clear what tests needs to be done on Windows/Linux to make it acceptable.

**Comment by klemens-morgenstern** [comment]
If you want to create a PR it would be better agains this repo, since all the CI is set up here (that's why there are two).

Testing this particular issue seems tricky though. But as long as removing the `WNOHANG` doesn't break any tests, I'd be happy to merge.

**Comment by amritanshujohri** [comment]
Ok as an alternative I will start with a timed wait instead, a small loop that runs for at-most 1 sec to reap the status, this way the total timed wait can be off by a second.

**Comment by kdescoteaux** [comment]
This problem affects  boost::process::detail::api::terminate(terminate.hpp) as well.
Up until boost 1.70 or so the waitpid after kill did not use WNOHANG, but WNOHANG was added (it's not clear why).
We immediately noticed zombie processes after upgrading from boost 1.68 to 1.76 due to the WNOHANG.

**Comment by klemens-morgenstern** [comment]
Closing in favor of boostorg/process#178
