### ISSUE TITLE
[question] will this resolve ASIO not safe when call fork issue?

### ISSUE THREAD

**Issue by laoshanxi** [klemens-morgenstern/boost-process#225]
I am using  microsoft/cpprestsdk which depend on boost ASIO. and I found an issue call fork() in ASIO server side (https://github.com/microsoft/cpprestsdk/issues/1535).

And currently, I used https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/Process.cpp to fork process now.  So can this issue be resolved when I replaced fork with this library?

Thanks so much

**Comment by klemens-morgenstern** [comment]
The `child` constructor (or any other process launching) will call `notify_fork` [here](https://github.com/boostorg/process/blob/14b294c10c1a8b9e5ce5b5eff6e039e852539345/include/boost/process/detail/posix/io_context_ref.hpp#L82) if you pass it into it. E.g.:

```cpp
auto & ioc = get_io_context_from_cpprestsdk();
boost::process::child("./foobar", ioc);
```

I don't know if that solves your issue, but it does sound like it.

**Comment by laoshanxi** [comment]
> 
> 
> The `child` constructor (or any other process launching) will call `notify_fork` [here](https://github.com/boostorg/process/blob/14b294c10c1a8b9e5ce5b5eff6e039e852539345/include/boost/process/detail/posix/io_context_ref.hpp#L82) if you pass it into it. E.g.:
> 
> ```c++
> auto & ioc = get_io_context_from_cpprestsdk();
> boost::process::child("./foobar", ioc);
> ```
> 
> I don't know if that solves your issue, but it does sound like it.

Thanks for your reply!

I have not tried this yet, if this is the case, I will try, 
I choosed ACE Process since that provide pipe/attach-able/block wait/none-block wait/... such features.

I will see whether those features can be found in this lib.

Many thanks!

**Comment by laoshanxi** [comment]
I tried notify_fork() around fork() but still can not resolve this issue.
Anyway, I would like to close this.
