### ISSUE TITLE
Win32: Incorrect handling of GetEnvironmentVariable return value

### ISSUE THREAD

**Issue by amerry** [klemens-morgenstern/boost-process#228]
The [GetEnvironmentVariable docs](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable) say:

> If lpBuffer is not large enough to hold the data, the return value is the buffer size, in characters, required to hold the string and its terminating null character and the contents of lpBuffer are undefined.

But the Win32 [native_environment_impl::get() implementation](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/environment.hpp#L60) doesn't check for the return value being _larger_ than the buffer size (it uses `if (size == buf_size)` as its "buffer too small" check).

The tests don't include getting a >4096 byte native environment variable value (in fact, they don't seem to really test manipulating the native environment at all).

If I get a chance, I'll put together an MR to test+fix this.

**Comment by klemens-morgenstern** [comment]
If you're still intent on filing the PR please to it against boostorg/process.
