### ISSUE TITLE
env.hpp is not standalone

### ISSUE THREAD

**Issue by theroyn** [klemens-morgenstern/boost-process#229]
Including ```boost/process/env.hpp``` results in the following error:
```error C3856: 'is_wchar_t': symbol is not a class template```
After a short investigation, I found that the symbol ```is_wchar_t``` is declared at ```boost/process/detail/traits/wchar_t.hpp```
What I think is that either
```#include <boost/process/detail/traits/wchar_t.hpp>```
or maybe even better
```#include <boost/process/detail/traits.hpp>```
should be added to ```env.hpp```.
I don't mind submitting a pr for this. Would that be alright?

**Comment by klemens-morgenstern** [comment]
Sure, submit it against boostorg/process
