### ISSUE TITLE
Boost 1.62/WinAPI

### ISSUE THREAD

**Issue by aaronovz1** [klemens-morgenstern/boost-process#30]
The documentation says boost 1.62 isn't released yet but it has been released. Is the separate WinAPI still required or can this be used with the default 1.62 release?

**Comment by klemens-morgenstern** [comment]
Sry forgot to update that. I recenetly added another winapi-function so the dependency went up to 1.63, i.e. the current develop branch of boost.winapi. That's the only dependency that needs to be current.

Thanks for checking the library out.

**Comment by aaronovz1** [comment]
Thanks for clarifying! I am waiting for this library to stabilize and will be using it in product soon.

**Comment by klemens-morgenstern** [comment]
I hope it's already there. It will be reviewed next week, so in two weeks we know if it will become part of boost. Unless it gets rejected, there won't be any major changes in the API.
