### ISSUE TITLE
Elaborate on platform dependent different results

### ISSUE THREAD

**Issue by teeks99** [klemens-morgenstern/boost-process#34]
In the documentation, on the Tutorial Page:

    This might lead to different results which are platform dependent.

What does this mean? Is this windows vs. linux or more obscure platforms? 

     The default depends on the system, but usually this will just write it to the output of the launching process. 

What should be expected on which systems. It seems like system variances in these items should get their own page of explanation with links to these spots.

Design page:

    On posix all those callbacks will be handles by this process, not the created one.

Is this different on windows? Other platforms?

**Comment by klemens-morgenstern** [comment]
Made it more precise in f70a609. Hope that suffices, if you're more confused, please let me know.
