### ISSUE TITLE
Error code like other functions?

### ISSUE THREAD

**Issue by teeks99** [klemens-morgenstern/boost-process#35]
In the documentation tutorial page, error code section it mentions:

    As with all other functions

What other functions? Standard library (clearly not *all* of those)? Others in boost process (*all* of those?)? How about "In a manner similar to XXX() and YYY(),", or just remove that phrase.

**Comment by klemens-morgenstern** [comment]
I changed it to "many other functions in this library" in 58023d7, you'll find the overloads in the reference.
