### ISSUE TITLE
Documentation - Reference for posix

### ISSUE THREAD

**Issue by teeks99** [klemens-morgenstern/boost-process#36]
It specifies that the posix items are in the boost::process::windows namespace, instead of the boost::process::posix namespace as the code suggests.
The warning note includes a link that is only relevant to the windows specific functionality. It should be a link to posix specific documentation for those items.

**Comment by klemens-morgenstern** [comment]
Fixed in 27431f3b3576bf9cffd352ea430ca63b8d94c097, I also updated the [doc](http://klemens-morgenstern.github.io/process/process/reference.html#header.boost.process.posix_hpp)
