### ISSUE TITLE
Incomplete tutorial example (nm/C++filt)

### ISSUE THREAD

**Issue by oxygene** [klemens-morgenstern/boost-process#38]
The Synchronous I/O example in the tutorial pipes the output of nm to c++filt. However, it is not specified that the output of c++filt should be made available in bp::ipstream is.

**Comment by oxygene** [comment]
Further, in the same example, the function is called read_demangled_outline and it takes a parameter (std::string & file). However, the parameter is not passed to the bp::child constructor of nm.

**Comment by oxygene** [comment]
And while you're at it, you could make "file" also a const-reference, as it is an input parameter only :)

**Comment by oxygene** [comment]
Let me now move on to the async IO examples:

I don't think you want to pass "g++" and "main.cpp" as parameters to boost::asio::async_read, but you intended to pass the pipe "ap"? Further, you should use the "bp::" namespace before "child" in all async examples for consistency.

Then, there is a note that wait() needs not to be called when passing an io_service instance. But in the code above, the wait is still called. This is confusing.

In the last async example with the future, there are some semantical changes that are not explained. Why is std_in closed? Why redirect std_out to null and now redirect std_err to the future? When reading, I was assuming that you are explaining different techniques to do the same, however with the last example the functionality changes and is confusing to the reader whether those changes are mandated by the use of std::future or are purely deliberate. Also, the exit_code is not retrieved at the end but it should for consistency with the previous examples.

**Comment by klemens-morgenstern** [comment]
1. I guess you mean "what the output is"? Well it's written in the doc as "Now we get the name from nm and we might want to demangle it, so we use input and output. nm has a demangle option, but for the sake of the example, we'll use c++filt for this." Not sure how I should make this more explicit in the example, but I'm of course open for suggestions.

2, 3 & 4 Oh, thanks, yeah, that's an error.

Ich frag mich ein wenig wie man so viel übersehen kann, das ist stellenweise peinlich. Dankeschön!

**Comment by oxygene** [comment]
1. See the code for read_demangled_outline(std::string & file). "bp::ipstream is" is declared, but not referenced in the declaration of "bp::child filt". Later it is correctly used in "std::getline(is, line)".

**Comment by klemens-morgenstern** [comment]
Oh right, thanks!

**Comment by klemens-morgenstern** [comment]
Fixed in e9a7dcb
