### ISSUE TITLE
environment is not passed to system(), spawn(), or child

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#48]
I'm trying to use boost::process with some sample playground stuff. Unfortunately I'm not able to inject or even re-use current process env. I'm pretty sure I'm overlooking something... I just picked code fragments from docs/tutorials.

I'm using linux, bp commit 9db6449044ad04747bfd9397d0340c0babfe389c

```
#include <boost/process.hpp>
#include <iostream>

int main(int argc, char** argv)
{
    namespace bp = boost::process; //we will assume this for all further examples

    bp::environment e = boost::this_process::environment();

    std::cout << "ENV size: " << e.size() << std::endl;
    std::cout << "ENV PATH: " << e.at("PATH").to_string() << std::endl;

    try {
        int r = bp::system("g++ -v", e);
        std::cout << "system: " << r << std::endl;
        return r;
    }
    catch (const std::exception& e)
    {
        std::cout<< "exception:" << e.what() << std::endl;
        return 1;
    }
}
```

result/stdout is:

```
ENV size: 96
ENV PATH: /usr/lib64/qt5/bin:/usr/bin:/home/pvanek/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/pvanek/src/drei/sepl-tools/scripts:/srv/qorus/bin
exception:execve failed: No such file or directory
```

**Comment by pvanek** [comment]
note, all works if I use: 
        int r = bp::system("/usr/bin/g++ -v");

**Comment by klemens-morgenstern** [comment]
I guess what you're trying to do is to let `system` determine the env - that doesn't work (only on windows in the cmd syntax to precise, i.e. `system("g++")`.
If you don't pass the `env` parameter it will inherit it anyway, that parameter (or the type) are there to modify it. If you want to search the path for an executable, you can use [search_path](http://klemens-morgenstern.github.io/process/boost/process/search_path.html) or (less recommended) [shell](http://klemens-morgenstern.github.io/process/boost/process/shell.html) - which will execute that through the shell.
You can also pass a modified environment to `search_path`.
I.e. your code would look like this:

```cpp
bp::system(search_path("g++"), "-v");
```

or (again not recommended, because of security reasons)

```cpp
bp::system("g++ -v", bp::shell);
```

**Comment by klemens-morgenstern** [comment]
Btw. I'm very happy you're trying the library. If you have any functionality you would like to see, I'll gladly add it provided it has similar implementations on both windows and posix. You can of course use the [extensions](http://klemens-morgenstern.github.io/process/boost_process/extend.html) capabilities to test that beforehand.

**Comment by klemens-morgenstern** [comment]
And I should maybe add this to the tutorial, because the reason for that is very clearly that this is not described there.

**Comment by klemens-morgenstern** [comment]
I took a look at your project, that looks very neat. You might wanna take a look as boost.asio, since that integrates with boost.process, for the I/O. That could be very useful if you want to buffer that to avoid deadlocks, which are a plague when using synchronous I/O.

**Comment by pvanek** [comment]
Thanks for hints. That's what I call support! Actually I want to inject some variables for child() instances. Is it possible?

**Comment by pvanek** [comment]
Meaning env variables of course

**Comment by klemens-morgenstern** [comment]
What do you mean by inject exactly? 
You can only modify the environment before the child has started, and there are two ways to do that:

```cpp
bp::environment e = boost::this_process::environment();
e["FOO"] = "BAR";
e["PATH"] += "/stuff";

system("thingy", e);
```

Or lazy:

```cpp
system("thingy", env["FOO"]="BAR", env["PATH"]+="/stuff");
```

If you want to modify the environment of a running child process, then no that's not possible. As far as I remember this would be insane hacking on windows and also not trivial on posix. However: you can obtain the native-handler or pid of a child process, so you're free to add that sort of thing. If that's possible in a portable way, I'll gladly add it to the lib.
