### ISSUE TITLE
child::wait() and child::terminate() in threaded app

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#52]
lets have a pseudocode simulating usage of boost::process in wrapped highly threaded environment

```
void some_func() {
    child c("tee", "-");
    start_thread_in_background: do_wait_thread(c); // it triggers do_wait_thread asynchrnonously

    do_some_expensive_thing();

    c->terminate();
}

void do_wait_thread(child *c) {
    c->wait(); // "waitpid(2) failed: No child processes" is raised here after terminate() is called
}
```

is it expected behavior?

**Comment by klemens-morgenstern** [comment]
Yes, this is expected. If the terminate is called the child handle is in valid. You would have to call wait prior to terminate. You could technically check with `c.running()` but that would be a race condition in your specific example.
If you want to use a highly-threaded environment, this seems like bad design; you launch a thread just to suspend it. I would recommend to take a look at `asio`, which might seem complex in the beginning, but will work flawlessly in this scenario.
