### ISSUE TITLE
boost::process::search_path() docs are confusing

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#53]
docs say:

```
 * The path must be a set of directories. Directories must be
 * separated by colons on POSIX and by semicolons on Windows.
 * If path is empty, the environment variable PATH is used.
```

but the default argument is of type:
```
const std::vector<boost::filesystem::path> path = ::boost::this_process::path()
```

When I post a path object with "foo:bar" for example (on linux) it is not split as docs say. I have to write my own "splitter" for it to fit std::vector<boost::filesystem::path>. Maybe the docs string is from a legacy boost::process version...

Fair enough, but please update the docs (or provide another helper function to parse a string to get path components) ;)

**Comment by klemens-morgenstern** [comment]
Thanks, yeah  I missed that change in the doc. Allowing a string there became unnecessary since you can also get a splitted value from the environment like this:

```
auto env = this_process::environment();
vector<path> vec = env["PATH"].to_vector();
```

**Comment by pvanek** [comment]
great. This one worked for me:

```
        bp::environment e;
        e["PATH"] = s->getBuffer(); // some strange string from upstream
        auto pathstr = e["PATH"].to_vector();
        std::vector<boost::filesystem::path> paths;
        for (auto n : pathstr) {
            paths.push_back(boost::filesystem::path(n));
        }
        ret = bp::search_path(command, paths);
```

**Comment by klemens-morgenstern** [comment]
Alright awesome if that works; that's basically what the `this_process::path` function does. Note that paths on windows use `wchar_t` since you can have names like "blödsinn.txt". So you might get an encoding error.

I could also add a `split_path` function, if you have a more or less common use-case here. I always try to keep the amount of public functions as small as possible. I also wouldn't be sure how to handle the `wchar_t`/ `char` problem there.

**Comment by pvanek** [comment]
there's more. The function should autodetect separator (':' vs ';') too.

My idea is to allow user to define custom path for searching the process' executable. Here is the code in language which is developed:

```
hash options = (
     "path" : "/srv/qorus/bin:/srv/qorus/sbin",  # complete avoid usage of env of current parent process and inject user search path
);
Program p("my_app", options);
p.wait();
```

or just append a custom dir into existing path:

```
hash options = (
    "path" : ENV.PATH + ":.", # it adds current dir into searchable path (let's not talk about security of '.' ;))
);
...
```

so for me split_path(), or maybe search_path(string, string_with_path) a little bit more, makes sense, but I can live without it ;)

**Comment by klemens-morgenstern** [comment]
Autodetection? Rather not, it would use the required way on the platform you're compiling on.

Dumb question: If you develop a language, why would you add a feature that is not portable? Why wouldn't you go for one syntax or create a custom one e.g.

```
"path" : ["/src/qorus/bin", "/src/qorus/bin"]
```

**Comment by pvanek** [comment]
yes, good point. It's one of mi TODOs to resolve with rest of guys here.

**Comment by klemens-morgenstern** [comment]
Just took a look at your language, the way I see it, you should just use a hash for the environment. If I understand this correctly, this should work:

```
env = { "FOO" : "BAR" ,
            "PATH" : ("/x", "/y", "/z")
          };
```

And with the `environment` type you can do this:

```
environment env;
std::vector<std::string> vec; //get it from qore
env["PATH"] = vec;
std::string foo; //get it from qore
env["FOO"] = foo;
```

**Comment by pvanek** [comment]
yes, that's exactly how is it done for env handling. Not for searchable paths.

I'm passing env vars as hash, eg. ( "env" : ( "FOO" : "bar" ), ), that's ok.
I just wanted to add something simpler for command resolving in custom paths. Probably I'll go with the list of strings approach

**Comment by klemens-morgenstern** [comment]
Alright then, btw. how's the encoding of a qore-string done? Because one of the reasons `search_path` takes a `vector` of `path` and not `string` is the encoding (on windows).
