### ISSUE TITLE
bp::start_dir unexpected behavior

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#56]
hi again. It's me, master or unusal usage of boost::process ;)

What is a purpose of bp::start_dir? It seems to me it's like "to setup an initial working dir" for child process.

But in this case it's somehow broken (?). See:

```
#include <boost/process.hpp>
#include <iostream>

namespace bp = boost::process;

int main(int argc, char** argv)
{
    bp::child c(  bp::search_path("test.sh")
                , bp::start_dir = "/tmp"
               );

    c.wait();
    int result = c.exit_code();
    return result;
}
```

then test.sh is (execute flag set on):

```
#!/bin/bash
echo $PWD
```

and run:

```
pvanek@linux-j415:~/oss/process/test-impl> export PATH=$PATH:.
pvanek@linux-j415:~/oss/process/test-impl> ./test-impl 
terminate called after throwing an instance of 'boost::process::process_error'
  what():  execve failed: No such file or directory
Aborted (core dumped)
```

coredump is fine, I just don't catch an exception. All is working if I omit start_dir option.
But I'd expect something different: test.sh should be run, but its starting dir would be /tmp...

**Comment by klemens-morgenstern** [comment]
More like the right guy to test it, I reckon. Your assumption is in fact correct and your example seems correct to me. 

If you use `start_dir` (on posix) you will need an absolute path to do so. Can you maybe verify that the path is set correctly and test.sh is found? I.e. just add

```
auto exe = bp::search_path("test.sh");
cout << "found Exe " << exe << endl;
```

**Comment by pvanek** [comment]
aha, that's the problem:

```
found Exe "./test.sh"
```

it works with fully qualified absolute path. I'll use boost::filesystem::absolute() in this case.

Can you add it do docs, please?

**Comment by klemens-morgenstern** [comment]
I'm actually not sure, adding `.` to path is the right move, since `PATH` is afaik a plain string. So I guess it should work if you add the absolute path to `PATH`.
At least `search_path` should add the absolute path and not only `.` then.

**Comment by pvanek** [comment]
adding '.' into PATH is just a quick hack for this testing. And sometimes it's valid input in various situations (actually it's not super secure, but it can be used)

**Comment by klemens-morgenstern** [comment]
Well yeah, but does the following work? Because that's in effect what you are doing.

```
mkdir foo
mkdir bar
# make test.sh
export PATH=$PATH:.
# here boost.process calls fork beforehand
cd ../bar
./test.sh
```

**Comment by pvanek** [comment]
yes, meaning no. That's what I will "workaround" with absolute() call

**Comment by pvanek** [comment]
anyway, feel free to take it as resolved with request for docs update ;)

**Comment by klemens-morgenstern** [comment]
Well I think that you got back `./test.sh` from `search_path` is because you added `.` to `PATH` in the first place. I.e. no doc update needed.
But then again I just realized I haven't done the last one yet, I'll be working on them on the weekend anyway.

But please continue to write issues when you run into problems, that really helps me.

**Comment by pvanek** [comment]
me too ;)
