### ISSUE TITLE
exit status seems to be incorrect in the case: posix and io_service

### ISSUE THREAD

**Issue by lebernie** [klemens-morgenstern/boost-process#60]
Hi,

When using boost::process::child in a posix environment and with a boost::asio::io_service, the retrieved exit status (child::exit_code()) will always be zero even if it is actually non-zero (in case of failure for example).
This can easily be verified with strace, looking for the wait* syscalls.

For example the following code should print "exit code: 1", but the result is "exit code: 0" :
```c++
    asio::io_service ios;
    std::future<std::string> data;

    bp::child c("/bin/false",
        bp::std_in.close(),
        bp::std_out > bp::null,
        bp::std_err > data,
        ios);

    ios.run();

    // std::cout << data.get() << std::endl;
    std::cout << "exit code: " << c.exit_code();
```

I think the problem in this case, is that WEXITSTATUS() is called twice on the exit status returned by the system. The first time in detail/posix/io_service_ref.hpp and the second time in detail/child_decl.hpp by eval_exit_status().
Hence, the value is always zero after the second time.

Here is a patch that seems to fix this issue :

```patch
diff -ru tmp/include/boost/process/detail/posix/io_service_ref.hpp boost-process-boost_review/include/boost/process/detail/posix/io_service_ref.hpp
--- tmp/include/boost/process/detail/posix/io_service_ref.hpp	2016-10-26 14:11:25.000000000 +0200
+++ boost-process-boost_review/include/boost/process/detail/posix/io_service_ref.hpp	2017-02-21 15:09:57.343266433 +0100
@@ -120,9 +120,9 @@
             ::wait(&status);
 
             std::error_code ec(ec_in.value(), std::system_category());
-            int val = WEXITSTATUS(status);
-            exit_status->store(val);
+            exit_status->store(status);
 
+            int val = WEXITSTATUS(status);
             for (auto & func : funcs)
                 func(val, ec);
         }
```

-- Thank you for your work.

**Comment by klemens-morgenstern** [comment]
Thanks, it certainly looks that way. I'll add it with a test.
