### ISSUE TITLE
When will boost-process be released?

### ISSUE THREAD

**Issue by bangusi** [klemens-morgenstern/boost-process#63]
Been waiting for a long time. Any chance it will be in boost-6.4?

**Comment by klemens-morgenstern** [comment]
It most definitely will be, it's already in the develop build.

**Comment by bangusi** [comment]
@klemens-morgenstern I do not see the library in beta1
https://dl.bintray.com/boostorg/beta/1.64.0.beta.1/source/
How come?

**Comment by klemens-morgenstern** [comment]
That is strange, I thought this was in there.
