### ISSUE TITLE
Safety of handlers post-fork handlers in child

### ISSUE THREAD

**Issue by sehe** [klemens-morgenstern/boost-process#65]
I came to this question because of the complications using `fork` in a multi-threaded application. 

How well does Boost Process accomodate multi threaded programs?

My understanding is that (on POSIX) Boost Process employs classical `[v]fork; exec[vpe]` patterns. These are fraught with limitations, and I'm very happy to use a library that encapsulate the pitfalls for me.

Some issues seem to suggest that thread safety has been a concern in designing some of the building blocks for Boost Process:

> ![image](https://cloud.githubusercontent.com/assets/324097/23574313/78146afc-007d-11e7-9f96-09e2dec176d9.png)

(from #2; issue #5 also mentions thread-safety (of `boost::asio::streambuf`)).

----

In just how far are multi threaded applications really facilitated?

 * does Boost Process have an equivalent of [something like `pthread_atfork`](http://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_atfork.html)
 * if applications use a malloc (replacement library) that internally locks, will it cause deadlock if the heap lock is/are held during fork?
 * Does Boost Process use [Boost Asio's fork notification hooks](http://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio.html#boost_asio.overview.posix.fork)?

**Comment by klemens-morgenstern** [comment]
I don't really see what influence the multi-threading of an application has to do with boost process, unldess you use pipes for inter-thread communication. The asynchronous operations are done with asio, thus they've got the same thread-safety.

 - yes, custom initializers as described [here](http://klemens-morgenstern.github.io/process/boost_process/extend.html) and [here](http://klemens-morgenstern.github.io/process/boost/process/extend/posix_executor.html)

-  I wouldn't know why, but that does depend on the malloc replacement.
- They are not (anymore) they caused problems when you used the same io_service for several launched processes. I'm not sure why I'd need to use them.

**Comment by sehe** [comment]
> I don't really see what influence the multi-threading of an application has to do with boost process

Fork is not safe in multithreaded programs. Period (pretty much). See e.g. http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

> Unless you use pipes for inter-thread communication

Ironically, this either has nothing to do with things OR it refers to one of the few allowed synchronization mechanisms POSIX actually [allows between parent and child processes of a fork](https://cr.yp.to/docs/selfpipe.html)

> The async operations are done with asio, thus they've got the same thread-safety

Understood. However, the `fork` is proprietary to this library, hence I'm seeking the specs here.

> 1. yes, custom initializers as described here and here

Very cool, I read about them once, but back then didn't realize their applicability. Good stuff.

> 2. I wouldn't know why, but that does depend on the malloc replacement

One example is this https://github.com/gperftools/gperftools/issues/178#issuecomment-133746071 excellent discussion on the subject; it echoes all the points made in the first link above.

However, it is important to realize that even GNU libc is susceptible to these issues (in a salient bit of trivia, their `execve` wrapper function at one point used `malloc`, leading to occasional deadlocks).

> 3. They are not (anymore) they caused problems when you used the same io_service for several launched processes. I'm not sure why I'd need to use them.

Good to know.

------

Tentative conclusions for me, at this time:

 - I can use custom initializer (extensions) to mimick our legacy pre/post fork handling. Thanks
 - The documentation could probably use some specific hints w.r.t. threaded applications.

**Comment by sehe** [comment]
Hmm. Reading http://www.boost.org/doc/libs/1_63_0/doc/html/boost_asio.html#boost_asio.overview.posix.fork again I think Boost Process should really be doing this:

> Boost.Asio supports programs that utilise the fork() system call. Provided the program calls io_service.notify_fork() at the appropriate times, Boost.Asio will recreate any internal file descriptors (such as the "self-pipe trick" descriptor used for waking up a reactor).

You don't want to risk deadlocking the process because of unfortunate syscall/signal timings. In a process that uses forking/execve heavily chances of that happening are actually not that slim.

If there's an issue with repeated use of that facility, it might be worth reporting with the Asio developers?

**Comment by klemens-morgenstern** [comment]
1. Ok, I should've been more specific what I mean: my understanding is, that you would have a problem with fork if you attempted to do anything multithreaded after the fork; but boost.process is only going to setup and launch the process using already safe tools as pipes and file-descriptors. So as far as I can see it, that should be safe. Now that's different for vfork, but I think there shouldn't be any problems either.
So to recap, the thread-problems from fork can occur when you fork a multithreaded-program with synchronization, because the forked one will only have one thread. That does not apply to process, since the launching of the subprocess is single-threaded, i.e. done from one thread. Thus leaving me unsure in which scenario there would be problems.

2. Yeah, that's the self-pipe I'm talking about. Actually if you build an extension you should use the [set_error](http://klemens-morgenstern.github.io/process/boost/process/extend/posix_executor.html#id310900-bb) of the executor, so that you`re error get's either send through the pipe, directly set in case of `vfork` or ignored if you passed `ignore_error`.

3. Regarding malloc: those are two different processes after the fork, so if there's a global lock which causes a deadlock this could in theory happen to every two processes. I'm not sure how that would be any particular problem to fork.
The only scenario I can think about is, that you have a call to `fork` while a process specific system-lock is still held which is copied over to the new process. Thus leaving the subprocess with a falsely aquired lock; BUT as far as I've understood the posix-standard that's a bug in the posix implementation (though please correct me if I'm wrong) and not a condition I would need to work around. And if I would need to, I wouldn't know how.

4. `notify_fork()` considering that the `io_service` is not referenced after the `fork` I still don't see how that's of any use. Secondly what's described (recreating file descriptors) is exactly what's messing up my I/O functions.
Again I don't see how the `io_service` is influenced by that. 

I find your questions a bit to general to really give a clear answer; I don't want to give a false assertion here.
Thus I say "I don't see it" as in "I can't think of a way that would happen.". But I might of course miss something, so if you either have a more defined scenario or an actual bug I can say something clearer about that.

**Comment by sehe** [comment]
You correctly point out how the `fork`+`exec` combo is fundamentally simpler landscape than just fork ("faux threading").

**ad. 3.** There's still a bit of relevancy in that the post-fork setup handlers run in that twilight zone between `fork` and `exec`. It is assuredly **not** a different process, then. You almost (but not entirely) dispel that worry with the fragment:

> but boost.process is only going to setup and launch the process using already safe tools as pipes and file-descriptors (ad. 1)

Firstly, this is not documented. It could be argued that it's redundant because anything else is unsafe (?). 
However, some of the guarantees are indeed unique to threaded applications (notably avoiding concurrent locks during `fork` as e.g. those in `malloc` implementations). It would be nice to have at least a "Note" about the guarantees made and those NOT made.

Secondly, this should probably be a highly visible caution in the section about extensions, as it is easy to break the functionality by doing unsafe calls in the post-fork handlers (`on_exec_setup` and `on_exec_error`).

---

**ad. 2** - excellent; I really appreciate all the details that this library obviously gets right. I'm really motivated to move to Boost Process for precisely this reason.

**Comment by klemens-morgenstern** [comment]
Well the precise description of the sequence in which the [posix_executor](http://klemens-morgenstern.github.io/process/boost/process/extend/posix_executor.html) handles the events is a bit hidden, but it's there.
Now in order for a malloc-problem to occur you would need a another than the launching thread calling malloc AND a malloc implementation with a single lock, that does not consider process IDs. Again, I think that's bad design and would guess not in conformity with the current posix standard. 
And of course the child is a new process after the fork; it has another ID, copied memory pages (at least virtually) and duplicated file descriptors. I'm not sure what else is needed to constitute a new process. 
`vfork` is a bit different, but that's explicitly marked as an extension.

Really I need more to go on, to make a qualified statement regarding that.

**Comment by sehe** [comment]
> Well the precise description of the sequence in which the posix_executor handles the events is a bit hidden, but it's there.

I'm not talking about the order of execution! I'm talking about the _safety_ of the operations between `fork` and `exec`. Nothing seems to be documented about this.

> Now in order for a malloc-problem to occur you would need a another than the launching thread calling malloc AND a malloc implementation with a single lock, that does not consider process IDs

Spot on! It can use a multitude of locks (like `tcmalloc`) though. No linux library will "consider process IDs" (I guess Win32 api makes that a logical assumption, but we're talking about POSIX here).

> Again, I think that's bad design and would guess not in conformity with the current posix standard.

As you probably have read, POSIX doesn't _say_ what functions are safe between `fork` and `exec`. It is generally _assumed_ that the functions POSIX deems `Async-Safe` can be considered safe here and most implementations work hard to achieve this.

Now, for example. GNU libc [documents it's `malloc` as `AS-Unsafe lock`](https://www.gnu.org/software/libc/manual/html_node/Basic-Allocation.html) which seems to agree with [POSIX 2008.1 §2.4.3](http://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_09), so really on everyday linux applications this applies to any application that uses threads.

I think it is really worth making sure that no code in the executor events allocates (or uses any other unsafe library calls).

> _Fun fact: the reason I'm actively adopting Boost Process is because our own `fork`/`exec` library had this kind of sporadic dead lock issues._

> And of course the child is a new process after the fork;

I said "in your sense". Let me be clearer: the process is not independent until the `exec`. It inherits a clone the program state (address space, thread stack, library globals etc.). Until the `exec` you have to keep this program state in mind. (Put otherwise: the child process will _evolve "indepently"_ but its initial state _"depends"_ 100% on the parent process state).

**Comment by sehe** [comment]
(PS. the claim that documentation bits were "a bit hidden" is too modest. I was positively surprised at the quality of the documentation there. It's one of the key reasons I want to use this library. Thanks again!)

**Comment by klemens-morgenstern** [comment]
Alright, I'll have to read up on that then; I should've learned by now that "they probably designed it right" is not a good assumption. I guess not letting it allocate isn't than big a problem and I'll document which initializer causes which syscall to occur. Can take a while though.
If I were to list all syscalls, would that suffice?

**Comment by klemens-morgenstern** [comment]
I completely lost track of this issue, is the problem still open for you? Problem is: I do use things like `std::string` in the forked child process, so it actually depends on the stdlib implementation. Not sure how to solve that.

**Comment by fcharlie** [comment]
@klemens-morgenstern 
Your can use execve and resolve filename before fork

see: http://www.man7.org/linux/man-pages/man7/signal-safety.7.html

**Comment by klemens-morgenstern** [comment]
I moved the execvpe before the fork to avoid alloations. The child process *might* still allocate when using `boost::error_code` if an error occurs OR if a user provides a custom handler.
