### ISSUE TITLE
windows_executor does not contain pid and exit_status members like the posix_executor does

### ISSUE THREAD

**Issue by pvanek** [klemens-morgenstern/boost-process#83]
hi,

is there some special reason for it?

http://klemens-morgenstern.github.io/process/boost/process/extend/windows_executor.html
vs.
http://klemens-morgenstern.github.io/process/boost/process/extend/posix_executor.html

**Comment by klemens-morgenstern** [comment]
The `exit_status` is there, the `pid` isn't because windows has that in a `proc_info`, i.e. you can get it as `proc_info.dwProcessId`.
Out of curiosity, what do you want to use the `pid` for in an extension?

**Comment by pvanek** [comment]
ah, thanks for info. The plan is only for logging/additional info.
