### ISSUE TITLE
Should environment be case insensitive in Windows?

### ISSUE THREAD

**Issue by kathoum** [klemens-morgenstern/boost-process#85]
Hi,
I have an issue with environment variables differing only by case in Windows.
If I understand correctly, the following code should spawn a child with a modified environment:

> `boost::process::environment env = boost::this_process::environment();`
> `env["PATH"] += some_path;`
> `boost::process::child child("program", env);`

However, when the current process has an environment variable named `"Path"` or `"path"`, the child process is created with two different environment variables: the pre-existing one unmodified, and the new one. This causes many problems, for example with DLL search paths (it looks like Windows arbitrarily chooses one of the two variables and ignores the other one).

It is my understanding that Windows handles environment variables ignoring differences in capitalization, at least when using the standard functions (getenv, _putenv, GetEnvironmentVariable, SetEnvironmentVariable); however, CreateProcess doesn't perform case normalization in the passed environment block, so the burden is on the caller.

I noticed that boost::this_process::path() does a case-insensitive search, and I think boost::process::environment should do the same when matching variable names in Windows.

**Comment by klemens-morgenstern** [comment]
I recently ran into that problem, but I thought that `GetEnvironmentVariable` does not ignore the case. I'll have to check this, but if they are not, I'll have to think of a better solution. I.e. a way to get or set case-insensitive.

**Comment by klemens-morgenstern** [comment]
Alright, environment variables are not case sensitive, so I'll make them all uppercase.

**Comment by klemens-morgenstern** [comment]
Ok, here's the problem: if you use the native function to set the environment it will overwrite case insensitive, but it will use the case of the last key to use it. E.g. if I set `X` and then `x` it will store it in `x` and remove `X`. That causes a problem for iteration, because there you still might have differences.

Any idea on how to solve that?

**Comment by kathoum** [comment]
Looking at `basic_environment_impl` in `detail/windows/environment.hpp`, I think it will do what we expect if `std::search` and `std::equal` are replaced with their case-insensitive variants (`boost::algorithm::iequals` and `boost::algorithm::ifind_first`), and if the lookup functions initialize the `entry_type` using the `key` argument instead of the found string.

What is the problem with iteration? `basic_environment_impl<Char>::set` already calls `reset` and then does a `reload`, so (if I understand correctly) the iterator invalidation effects should not change. I think a sensible goal is to produce the same observable behavior as `native_environment`.

Do you think case sensitivity should be tied to the platform (posix vs windows) or it's better to add a new template parameter to basic_environment (with platform-dependent default)?

**Comment by deadash** [comment]
you can use it like this:
```
bp::environment env = boost::this_process::environment();
auto itr = std::find_if(env.cbegin(), env.cend(),
	[&](const auto & e)
{return "PATH" == ::boost::to_upper_copy(e.get_name()); });
if (itr == env.cend()) { env["PATH"] += some_path; }
else {
	env[itr->get_name()] += some_path;
}
```

**Comment by klemens-morgenstern** [comment]
to close the issue: yet the enviroment should be case sensitive on windows, because windows handles it that way. The loopup for path is case-insensitive though.
