### ISSUE TITLE
[windows] Use PATHEXT for expanding executable extensions.

### ISSUE THREAD

**Issue by pravic** [klemens-morgenstern/boost-process#91]
Currently it uses hardcoded limited [set of them](https://github.com/boostorg/process/blob/develop/include/boost/process/detail/windows/search_path.hpp#L35): `"", ".exe", ".com", ".bat"`, but it is not correct.

**Comment by klemens-morgenstern** [comment]
What's the error? Which other types should I add?

**Comment by pravic** [comment]
Error? For example, if someone adds one more extension there, like `.py` in `PATHEXT=.COM;.EXE;.CMD;.BAT;.VBS;.PY`, so the following command will fail:
```cpp
// spawn 2to3.py
bp::spawn(bp::search_path("2to3"), "--help");
```
Or a bit more real: [slmgr](https://techjourney.net/slmgr-commands-and-options-for-windows-product-key-kms-token-ad-activation/) command - by default `PATHEXT` contains VBS, JS, WSH extensions and so on.

**Comment by klemens-morgenstern** [comment]
Oh, yeah. That would be the right approach. I'll add this. Thanks!

**Comment by klemens-morgenstern** [comment]
Alright, there it is: https://github.com/klemens-morgenstern/boost-process/commit/712ebf772b632b9e345a55827be7733140f7173c

Now the problem is that the extensions are upper case, so it looks for both upper case and lower case. It will not work for something mixed, e.g. `foo.eXe` - do you think that this will cause a problem. Because if I have to search for every combination this will get really slow.

**Comment by pravic** [comment]
Why do you care about extension case on Windows, where paths are case-insensitive by default?

Also I think that `sh_get_file_info` works only with executables (MZ/NE/PE according to MSDN), but not with scripts which can be executed by `HKCR\<type>\shell\open\command` registry assotiation.

**Comment by klemens-morgenstern** [comment]
Paths are case sensitive, at given my API. If I only check for `foo.EXE` and only `foo.exe` exists `boost::filesystem::is_regular_file` will fail. At least I think I had this behaviour, I'm going to double check that.

I think you might be right about the `sh_get_file_info` - that was inherited from an older process version. I'll add a few tests.

**Comment by pravic** [comment]
> At least I think I had this behaviour, I'm going to double check that.

Well, since we have a small chance that someone can excplicitly set [case-sensitivity for NTFS](https://technet.microsoft.com/en-us/library/cc725747(v=ws.11).aspx), it is safer to leave case-awareness [as is](https://github.com/klemens-morgenstern/boost-process/issues/91#issuecomment-296458806).

Thanks for understanding :) Anyway, this library is very useful.

**Comment by klemens-morgenstern** [comment]
Sry lost a bit track of my issues, I think this has been solved since a while ago. Feel free to reopen if there are issues.
