### ISSUE TITLE
limit file descriptors functionaliy

### ISSUE THREAD

**Issue by klemens-morgenstern** [klemens-morgenstern/boost-process#92]
Add the functionality recommended by @nat-goodspeed to limit the amount of file descriptors/handles inherited by the child.

**Comment by sehe** [comment]
An early heads up: @klemens-morgenstern  and I discussed this a while back on Slack. I decided to wait for this feature in Boost 1.65.0 but yesterday a production issue surrounding inherited FDs came up.

On the Boost Process the scheduler slipped, so it looked like I will /need/ to fix this sooner. Here's the prototype of the fix that I will take for our codebase, and it might serve as inspiration here:

https://github.com/sehe/boost-process/commit/3d1f77b38b8e9cebd1124615ac2b6269a3de89b0#commitcomment-22387163 (This is expressly NOT a PR, as it is premature IMO)
