### ISSUE TITLE
doesn't compile with VS 2013

### ISSUE THREAD

**Issue by frederich** [klemens-morgenstern/boost-process#96]
https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/config.hpp#L50

VS 2013 has no noexcept support.

**Comment by klemens-morgenstern** [comment]
Along with ref-qualifiers, which cannot be removed by design.
This library does require C++11 support, so VS 2013 is not supported. I went down to C++11 from C++14 already to allow VS 2015.

**Comment by frederich** [comment]
Not usable in industrial applications, what's a pity.

**Comment by klemens-morgenstern** [comment]
I'd be surprised if the whole industry is stuck with VS2013 four years after release. I'm following a standard here. 
If you need a version that does compile on VS2013 just fork the library and add the workarounds you need. I won't sacrifice good design for an outdated compiler and I don't understand why it is so hard to see, that open-source does allow you to change the library for your needs.
