### ISSUE TITLE
[windows] Problem with exe with spaces

### ISSUE THREAD

**Issue by baysmith** [klemens-morgenstern/boost-process#97]
The wstring version of build_args (in detail/windows/basic_cmd.hpp) is missing the check for spaces in the exe and quoting if spaces found. Without the quoting, I was seeing the exe run, but the arguments passed to it were not correct. The string version of the function has the check. Putting similar code in the wstring function fixed the problem for me.

I also noticed that in the wstring version of build_args `std::find(arg.begin(), arg.end(), ' ');` should probably have an L before the space character literal (i.e. `std::find(arg.begin(), arg.end(), L' ');` ).

Thanks for this library and congratulations on getting it integrated in boost.

**Comment by klemens-morgenstern** [comment]
Thanks, should be done.
