### ISSUE TITLE
create pipe failed on window.

### ISSUE THREAD

**Issue by deadash** [klemens-morgenstern/boost-process#98]
in `\process\detail\windows\async_pipe.hpp`
the function `inline std::string make_pipe_name()`
should change the `cnt` to random number,

like this. add
```
	name += "_";
	srand(time(0));
	name += std::to_string(rand() % 1000);
```

**Comment by klemens-morgenstern** [comment]
It should not, that would add the possibilitynof duplicates. Whike the incremented includes the pid

**Comment by deadash** [comment]
When I use two separate threads in a process and the two separate threads are in two dlls(which makes the cnt variable not shared)， when using `async_pipe`, the function will throw exception(call the threads one by one will produce), and the exception cannot be caugh(so the execute exit.). **I do not know how to catch it**. So I modified it to random number that makes the possibility of error become very low (will not repeat).

**Comment by klemens-morgenstern** [comment]
That's not a good solution either. Adding the thread-id to the name would be possible though.

**Comment by deadash** [comment]
This could be two dll in the same thread, it will be a problem at this time.

**Comment by klemens-morgenstern** [comment]
Yeah, but rand doesn't solve that either. I fear the only solution would be to put the `make_pipe_name` in a dll shared by those two - that's a downside of having a header-only library.

**Comment by deadash** [comment]
Perhaps I should put the called parts of the two dlls into one dll for sharing according to what you said, but there will be hidden danger for those who are unwitting, the rand may have downsides, but it's still a quick temporary solution. Otherwise, other solutions will be more complicated than ever.

**Comment by deadash** [comment]
I patch it like this.
```
#ifdef BOOST_PROCESS_WINDOW_MAKE_PIPE_NAME_FUNC

	std::string make_pipe_name();

#else
	inline std::string make_pipe_name()
	{
		std::string name = "\\\\.\\pipe\\boost_process_auto_pipe_";

		auto pid = ::boost::detail::winapi::GetCurrentProcessId();

		static unsigned long long cnt = 0;
		name += std::to_string(pid);
		name += "_";
		name += std::to_string(cnt++);
		return name;
	}
#endif
```

then, use it.
```
#define BOOST_PROCESS_WINDOW_MAKE_PIPE_NAME_FUNC
#include <boost/process.hpp>
```
and implement the function
```
namespace boost { namespace process { namespace detail { namespace windows {
	std::string make_pipe_name()
	{
		std::string name = "\\\\.\\pipe\\boost_process_auto_pipe_";

		auto pid = GetCurrentProcessId();

		static unsigned long long cnt = 0;
		name += std::to_string(pid);
		name += "_";
		name += std::to_string(cnt++);
		name += "_";
#ifdef ONE
		name += "one"';
#else
		name += "two";
#endif
		return name;
}}}}}
```

**Comment by klemens-morgenstern** [comment]
You should be able to just do that this way:

```cpp
asio::io_service ios;
bp::async_pipe ap(ios, my_name_generator());
```

**Comment by deadash** [comment]
how can I know when the process exit.
Now I just use the error code of read pipe to get it.
And the function of on_exit never called.

**Comment by egorpugin** [comment]
I see very frequent fails on this
```
create_named_pipe(\\.\pipe\boost_process_auto_pipe_13760_0) failed
```
from https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/async_pipe.hpp#L273

I did not dig much into it yet, but problem exists.

@klemens-morgenstern, I assume that this is library issue, not OS/my code/else side issue, right?
I see this on very low workloads such as running 8 processes (on 8 threads with 8 logical cores processor, 1 process per thread).

**Comment by egorpugin** [comment]
The most suspicious place is https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/windows/async_pipe.hpp#L29
Starting multiple processes simultaneously in large number of threads will lead to race on that counter. I'll make it atomic locally and test.

**Comment by klemens-morgenstern** [comment]
Given that the PR is merged, is the issue still open?
