### ISSUE TITLE
Child wait_for does not work work as intended

### ISSUE THREAD

**Issue by Taredon** [klemens-morgenstern/boost-process#99]
Hello there,
I have the following odd behavior:
- Calling wait_for with error_code does work as intended
- Calling wait_for without error_code does return immediately

Consider the following sample:
**_OS:_** Debian GNU/Linux 8.8 (jessie)
**_Architecture:_** 64bit
**_GCC Version:_** gcc version 4.9.2 (Debian 4.9.2-10)
**_Boost Version:_** 1.64.0
**_Compile flags:_** g++ -std=c++0x -D_cplusplus=201103L -I/opt/boost/current/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Testing.d" -MT"src/Testing.o" -o "src/Testing.o" "../src/Testing.cpp"
**_Linking:_** g++ -L/opt/boost/current/lib -o "Testing"  ./src/Testing.o   -lboost_system-mt -lpthread

```
#include <iostream>
#include <thread>
#include <boost/process.hpp>

int main() {
	boost::process::child c(
		boost::process::exe = "/bin/sleep",
		boost::process::args= {"5"}
	);

	auto running = true;
	while (running) {
		// Method 1
//		std::error_code ec;
//		const auto isDone = c.wait_for(std::chrono::seconds(1), ec);

		// Method 2
		const auto isDone = c.wait_for(std::chrono::seconds(1));

		if (!isDone) {
			std::cout << "Fork is still doing hard work..."
					<< std::endl;
		} else {
			std::cout << "Fork is done: " << c.exit_code()
					<< std::endl;
		}

		running = !isDone;
	}
	c.wait();

	return 0;
}
```
Method 1 using the error code works as expected and produces the following output:
```
Fork is still doing hard work...
Fork is still doing hard work...
Fork is still doing hard work...
Fork is still doing hard work...
Fork is done: 0
```

Method 2 however immediately returns (seemingly detaches the fork since its running and completing without any problems in the background, after the original program has already terminated), as well as producing the following output:
```
Fork is done: 0
```

Does anyone have any suggestions to this odd behavior?

**Comment by klemens-morgenstern** [comment]
I just checked the code, and the code as well as your example look correct to me. So I have no clue.

What happens if you change `auto running = true;` to `auto running = c.running();`?

**Comment by Taredon** [comment]
Making this change results in the exact same behavior as before. 
I also was quite sure the code should be correct. Especially since i checked the wait_for implementions in boost process which only differ from each other in the error handling behavior which shouldn't make any difference.

**Comment by klemens-morgenstern** [comment]
That is really strange, it's obviously faulty behaviour, but I have no clue. Do you have the same behaviour if you increase the time from 5 seconds to let's say 30?

**Comment by Taredon** [comment]
Behavior is the same with increased sleeps. The detached fork just stays longer after the main program terminated.

Whats even stranger is the fact that compiling the same code with these compilers:
- gcc version 5.4.1 20170519 (Debian 5.4.1-11)
- gcc version 6.3.0 20170516 (Debian 6.3.0-18)

results in the following:
```
Fork is still doing hard work...
Fork is done: 0
```

Guess im going check out what other compilers produce  on different OS, maybe theres a bug in the new debian.

**Comment by klemens-morgenstern** [comment]
Please let me know if you find something. It is sadly sometimes the case that it's the OS doing something strange, especially for things like `/bin/sleep` - maybe it works reliable when used with `boost::process::shell`, i.e. 
```cpp
boost::process::child c("sleep 5", boost::process:.shell);
```

**Comment by Taredon** [comment]
Maybe you are right about the sleep stuff, I was using it only for testing purposes anyway.

For your idea about the process execution: Directly passing the args (5 seconds) in the command results in issues due to boost not being able to find the executables path.

Turns out I have the same problem on my Ubuntu machine (Ubuntu 16.04.2 LTS, 64bit, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)). Results in the same issue as the 5.4.1/6.3.0 debian gcc builds. 

**_Edit:_** Also to exclude the sleep stuff I used some other long running command (some pings to google), which resulted in the same behavior again. Would be quite interesting if this is a problem on my side, or whether others experience the same issue.

**Comment by klemens-morgenstern** [comment]
Oh, well if you use shell it should actually find it in the path. I'm really baffled by the problem, and it's especially bad if it's not only `/bin/sleep`. Now it could just be that the current process gets suspended until the child ran through - but that would not explain the difference between the two functions. So I have no clue what's happening there, especially since the sys-calls are equal for both cases.

I'd do some testing myself, but I'd just run it on a VM, so that doesn't help much either.

**Comment by Taredon** [comment]
Would be quite interesting what results you get though. However I also only tested it in VMs so far, since I have no native installation.

**Comment by klemens-morgenstern** [comment]
Ok, I'll take some time to test in the next days.

**Comment by Taredon** [comment]
By any chance: Is there the possibility, that wait_for in both ways (w/wo ec) does not deal with "child still running" results (return of waitpid == 0)?

When I attempted to insert some logging, the issue started occuring on the wait_for with ec method. For simple checks i added "|| (ret == 0)" to the while loop. After that, both wait_for methods worked as expected. 

From what I can see I would assume the following:
1. Someone calls wait_for
2. timeout_occured is set to false
3. while loop breaks due to "ret == 0", meaning child is still running
4. timeout_occured is still false since noone changed it and the process seems to think, it has terminated

Doesnt explain why wait_for with ec worked in the first place? Maybe there are some strange timing constellations?

**Comment by klemens-morgenstern** [comment]
Wouldn't 3 be covered by `(ret == -1) && !WEXITSTATUS(status)` ? That's at least the assumption there, but you might be right. I just wonder if I misunderstood the function.

**Comment by Taredon** [comment]
Im not quite sure since WIFEXITED which is used in the while loop says:
_This macro returns a nonzero value if the child process terminated normally with exit or _exit._ 

I dont think this deals with no termination at all?

Where do you see WEXITSTATUS?

**Comment by Taredon** [comment]
Another Update:

I had the chance to try the sample on my main working vm at work. Turns out, the sample runs quite fine there.

**_VM Specs:_**
**_OS:_** Ubuntu 14.04.5 LTS
**_Architecture:_** 32bit
**_GCC Version:_** gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~14.04.1) 

However I found that quite suspicious, so I started figuring out the differences on those machines. Most important of all the vm at work has been running quite a bit longer under heavy use.

What I have found out so far is that in `wait_for_exit.hpp` as well as some other places neither `pid_t ret` nor `int status` is initialized. When i initialized both values with `0`, the vm at work showed the exact same behavior as the other vm where I tested the sample before. 

Could it be the issue that if `ret == 0` when using `waitpid`, the status variable is not initialized by anyone  and causes undefined behavior when being checked at the end of the loops?

**Comment by klemens-morgenstern** [comment]
Yeah that could be it. I am to used to those values being zero when not initialized, but that's sloppy.

**Comment by Taredon** [comment]
Something along this would fix the issue with the wrong waitpid check:

```
    bool eintr_occured = false;
    bool still_running = false;
    bool time_out_occured = false;
    do
    {
        ret = ::waitpid(p.pid, &status, WUNTRACED | WNOHANG);
        if (std::chrono::system_clock::now() >= time_out)
        {
            time_out_occured = true;
            break;
        }

        eintr_occured = ((ret == -1) && (errno == EINTR));
        still_running = (ret == 0);
    } 
    while (eintr_occured || still_running);
```

However this would result in the insane spam loop I mentioned ahead, since waitpid would return immediately.

**Comment by klemens-morgenstern** [comment]
Does 09381034276ce76eedd6936ae330159dec9938d9 solve the issue?
